export const BLUEPRINT_ID = "as.phase3.curriculum.2026-07";
export const BLUEPRINT_VERSION = "1.0.0-draft";
export const GENERATED_ON = "2026-07-19";

export const SOURCE_TYPES = Object.freeze({
  scripture: "Sacred Scripture",
  catechism: "Catechism of the Catholic Church",
  council: "Ecumenical council",
  papal: "Authoritative papal document",
  dicastery: "Authoritative dicastery document",
  fathers: "Church Fathers",
  doctors: "Doctors of the Church",
  liturgy: "Authoritative liturgical text",
  canonLaw: "Code of Canon Law or Eastern canon law",
  history: "Primary historical source",
  catholicScholarship: "Recognised Catholic scholarship",
  academic: "Reputable academic scholarship",
  comparative: "Official comparative-tradition source",
  science: "Peer-reviewed scientific source or consensus statement",
});

export const GRAPH_CATEGORIES = Object.freeze([
  "islam",
  "judaism",
  "secular",
  "pagan",
  "eastern",
  "protestant",
  "historical",
  "canon",
  "christology",
  "trinity",
  "papacy",
  "eucharist",
]);

export const DOCTRINAL_CLASSIFICATIONS = Object.freeze([
  "dogma",
  "doctrine",
  "discipline",
  "theological_opinion",
  "historical_claim",
  "philosophical_claim",
  "scientific_claim",
]);

export const progressionProfiles = Object.freeze({
  standard: [
    { key: "foundations", name: "Foundations", purpose: "Establish the Catholic claim, vocabulary, place in the hierarchy of truths, and beginner mental model." },
    { key: "distinctions", name: "Distinctions", purpose: "Prevent category errors by separating dogma, doctrine, discipline, opinion, and neighboring concepts." },
    { key: "evidence", name: "Evidence", purpose: "Integrate Scripture, Tradition, Magisterium, history, and reason in a cumulative case." },
    { key: "objections", name: "Objections", purpose: "State serious alternatives fairly, identify internal variations, and answer their strongest forms." },
    { key: "synthesis", name: "Synthesis", purpose: "Build a concise, charitable apologetic explanation and connect doctrine to worship and life." },
  ],
  historical: [
    { key: "orientation", name: "Historical Orientation", purpose: "Establish chronology, geography, actors, terminology, and the doctrinal questions at stake." },
    { key: "sources", name: "Primary Sources and Distinctions", purpose: "Distinguish primary evidence, later interpretation, reception, and anachronistic claims." },
    { key: "development", name: "Doctrinal Development", purpose: "Trace continuity, legitimate development, controversy, and authoritative settlement." },
    { key: "contested", name: "Contested Narratives", purpose: "Compare rival historiographies and answer common polemical simplifications." },
    { key: "synthesis", name: "Historical-Apologetic Synthesis", purpose: "Form a sourced account that neither sanitises nor caricatures Church history." },
  ],
  lab: [
    { key: "brief", name: "Case Brief", purpose: "Define the question, audience, burden of proof, and doctrinal boundaries." },
    { key: "dossier", name: "Source Dossier", purpose: "Assemble, rank, verify, and annotate primary and secondary sources." },
    { key: "construction", name: "Case Construction", purpose: "Build arguments, anticipate rebuttals, and choose proportionate claims." },
    { key: "simulation", name: "Dialogue or Live Simulation", purpose: "Practise timed, charitable explanation under realistic constraints." },
    { key: "debrief", name: "Debrief and Mastery", purpose: "Audit accuracy, rhetoric, omissions, and next-study needs." },
  ],
  bible: [
    { key: "context", name: "Canonical and Historical Context", purpose: "Locate the book in the Catholic canon, salvation history, literary setting, and liturgical reception." },
    { key: "structure", name: "Literary Structure", purpose: "Map the book's movements, genres, principal figures, and argument." },
    { key: "theology", name: "Theological Themes", purpose: "Trace the book's teaching in the unity of Scripture and the hierarchy of truths." },
    { key: "difficult-texts", name: "Difficult Texts and Questions", purpose: "Address interpretive disputes, moral difficulties, and common proof-texting errors." },
    { key: "synthesis", name: "Christological and Catholic Synthesis", purpose: "Read the book in Christ, the Church's liturgy, doctrine, moral life, and prayer." },
  ],
});

const S = SOURCE_TYPES;
const coreAudience = ["beginners", "catechumens and converts", "Catholics seeking systematic formation", "casual quiz players"];
const specialistAudience = ["formed Catholics", "catechists", "apologists", "advanced learners"];
const scholarlyAudience = ["advanced learners", "apologists", "catechists", "source researchers"];

function groupId(subjectId, groupKey) {
  return "grp." + subjectId + "." + groupKey;
}

function subject(definition) {
  if (!Array.isArray(definition.lessonTopics) || definition.lessonTopics.length !== 10) {
    throw new Error("Subject " + definition.id + " must define exactly ten lesson topics");
  }
  return Object.freeze({
    profile: "standard",
    audience: specialistAudience,
    difficulty: "intermediate",
    classifications: ["doctrine"],
    sources: [S.scripture, S.catechism, S.council, S.papal, S.fathers, S.catholicScholarship],
    traditions: [],
    graphCategories: [],
    reviewRisk: "medium",
    cccParts: ["I"],
    prerequisiteGroupIds: [],
    requiredPriorConcepts: [],
    optional: false,
    expertChallenge: false,
    liveQuizEligible: true,
    ...definition,
  });
}

export const subjectDefinitions = [
  subject({
    id: "catholic-foundations", name: "Catholic Foundations", programmeId: "core-foundation", order: 1,
    description: "Introduces the Gospel-centred shape of Catholic faith, the hierarchy of truths, doctrinal classifications, and the habits needed for charitable apologetics.",
    audience: coreAudience, difficulty: "foundation", cccParts: ["I", "II", "III", "IV"],
    classifications: ["dogma", "doctrine", "discipline", "theological_opinion"],
    sources: [S.scripture, S.catechism, S.council, S.liturgy],
    requiredPriorConcepts: ["none"], reviewRisk: "low", graphCategories: ["christology"],
    lessonTopics: ["The Gospel at the Centre", "The Catechism's Four-Part Symphony", "Dogma, Doctrine, Discipline, and Opinion", "The Hierarchy of Truths and Doctrinal Proportion", "Scripture, Tradition, and Magisterium at First Glance", "Creed, Worship, Life, and Prayer as One Whole", "Why Catholics Need Apologetics", "Avoiding Proof-Texting, Triumphalism, and False Certainty", "Giving a Two-Minute Account of Catholic Faith", "Formation before Argument"],
  }),
  subject({
    id: "revelation-faith", name: "Revelation and Faith", programmeId: "core-foundation", order: 2,
    description: "Explains God's self-revelation, the deposit of faith, the obedience of faith, and the relation of grace, reason, and ecclesial reception.",
    audience: coreAudience, difficulty: "foundation", cccParts: ["I"],
    prerequisiteGroupIds: [groupId("catholic-foundations", "synthesis")],
    requiredPriorConcepts: ["Gospel", "hierarchy of truths", "doctrinal classifications"],
    graphCategories: ["canon"], reviewRisk: "medium",
    lessonTopics: ["God Speaks and Gives Himself", "The Deposit of Faith", "Public Revelation and Private Revelation", "Faith, Reason, Certainty, and Mystery", "The Biblical Pattern of Revelation and Response", "Dei Verbum and the Transmission of Revelation", "Is Faith Blind or Irrational?", "Has Revelation Been Corrupted?", "Explaining Catholic Authority without Circularity", "The Obedience of Faith in Christian Life"],
  }),
  subject({
    id: "scripture-canon", name: "Scripture and Canon", programmeId: "core-foundation", order: 3,
    description: "Forms learners in inspiration, truth, interpretation, canon formation, and the ecclesial reading of the Catholic Bible.",
    audience: coreAudience, difficulty: "foundation", cccParts: ["I"],
    prerequisiteGroupIds: [groupId("revelation-faith", "distinctions")],
    requiredPriorConcepts: ["revelation", "Tradition", "Magisterium"], graphCategories: ["canon"], reviewRisk: "high",
    sources: [S.scripture, S.catechism, S.council, S.fathers, S.history, S.catholicScholarship, S.academic],
    traditions: ["Catholic", "Eastern Orthodox", "Protestant"],
    lessonTopics: ["What Catholics Mean by Inspiration", "How to Read Scripture in the Church", "Inerrancy, Truth, Genre, and Authorial Intention", "Canon, Text, Translation, and Lectionary", "Jesus and the Apostolic Use of Scripture", "From Israel's Scriptures to the Catholic Canon", "Did the Church Add Books to the Bible?", "Does Tradition Compete with Scripture?", "A Cumulative Case for the Catholic Canon", "Reading the Bible Liturgically and Prayerfully"],
  }),
  subject({
    id: "salvation-history", name: "Salvation History", programmeId: "core-foundation", order: 4,
    description: "Surveys creation, covenant, Israel, kingdom, exile, promise, Christ, Church, and consummation as the unified drama of salvation.",
    audience: coreAudience, difficulty: "foundation", cccParts: ["I"],
    prerequisiteGroupIds: [groupId("scripture-canon", "foundations")],
    requiredPriorConcepts: ["biblical canon", "covenant", "typology"], graphCategories: ["canon", "historical", "christology"],
    lessonTopics: ["Creation, Fall, and Promise", "The Covenant Shape of the Bible", "Covenant, Testament, Kingdom, and Typology", "Israel, Church, Fulfilment, and Supersessionist Errors", "Adam, Noah, Abraham, Moses, and David", "Exile, Prophets, Wisdom, and Messianic Hope", "Is Typology Arbitrary?", "Does the Church Replace Israel?", "Telling the Whole Biblical Story in Ten Minutes", "Finding One's Life within Salvation History"],
  }),
  subject({
    id: "god-trinity-creation", name: "God, Trinity, and Creation", programmeId: "core-foundation", order: 5,
    description: "Introduces the one God, divine attributes, the Trinity, creation, providence, angels, and the human person in God's image.",
    audience: coreAudience, difficulty: "foundation", cccParts: ["I"],
    prerequisiteGroupIds: [groupId("revelation-faith", "synthesis"), groupId("salvation-history", "foundations")],
    requiredPriorConcepts: ["revelation", "creation", "covenant"], classifications: ["dogma", "doctrine", "theological_opinion"],
    graphCategories: ["trinity"], reviewRisk: "high",
    lessonTopics: ["The One God Who Creates and Calls", "Father, Son, and Holy Spirit", "Nature, Person, Essence, and Relation", "Creation, Providence, Freedom, and Secondary Causes", "Biblical Monotheism and Trinitarian Revelation", "The Creeds on God, Creation, and Trinity", "Is the Trinity a Contradiction?", "Does Creation Conflict with Science?", "Confessing One God in Three Persons", "Living as Creatures and Adopted Children"],
  }),
  subject({
    id: "christ-paschal-mystery", name: "Christ and the Paschal Mystery", programmeId: "core-foundation", order: 6,
    description: "Centres the curriculum on the Incarnation, ministry, Passion, death, Resurrection, Ascension, and saving lordship of Jesus Christ.",
    audience: coreAudience, difficulty: "foundation", cccParts: ["I", "II"],
    prerequisiteGroupIds: [groupId("god-trinity-creation", "synthesis"), groupId("salvation-history", "evidence")],
    requiredPriorConcepts: ["Trinity", "covenant", "Messiah", "typology"], classifications: ["dogma", "doctrine", "historical_claim"],
    graphCategories: ["christology", "historical"], reviewRisk: "critical",
    lessonTopics: ["Jesus Christ, True God and True Man", "The Paschal Mystery as the Centre", "Person, Nature, Will, Mission, and Mediation", "Redemption, Atonement, Sacrifice, and Victory", "The Gospel Witness to Jesus", "The Historical and Apostolic Case for the Resurrection", "Was Jesus Only a Teacher or Prophet?", "Did the Resurrection Become a Later Legend?", "Explaining Who Jesus Is and What He Has Done", "Union with Christ Crucified and Risen"],
  }),
  subject({
    id: "church-grace-sacraments", name: "Church, Grace, and Sacramental Life", programmeId: "core-foundation", order: 7,
    description: "Introduces the Church as Christ's Body and sacrament, apostolic ministry, grace, justification, and the seven sacraments.",
    audience: coreAudience, difficulty: "foundation", cccParts: ["I", "II", "III"],
    prerequisiteGroupIds: [groupId("christ-paschal-mystery", "synthesis")],
    requiredPriorConcepts: ["Christ's mission", "Paschal Mystery", "Holy Spirit"],
    classifications: ["dogma", "doctrine", "discipline"], graphCategories: ["papacy", "eucharist"], reviewRisk: "critical",
    traditions: ["Catholic", "Eastern Orthodox", "Protestant"],
    lessonTopics: ["The Church in God's Saving Plan", "Grace and the Seven Sacraments", "Church, Kingdom, Communion, and Institution", "Grace, Justification, Merit, and Cooperation", "The Apostolic Church in Scripture and Early Witness", "Christ Acting in the Sacraments", "Can a Human Church Claim Divine Authority?", "Do Catholics Earn Salvation or Trust Rituals?", "Connecting Church, Grace, and Sacrament", "Living from Baptism and Eucharist"],
  }),
  subject({
    id: "moral-prayer-foundations", name: "Moral Life and Prayer Foundations", programmeId: "core-foundation", order: 8,
    description: "Completes the foundation route through beatitude, freedom, virtue, conscience, sin, commandments, prayer, and the universal call to holiness.",
    audience: coreAudience, difficulty: "foundation", cccParts: ["III", "IV"],
    prerequisiteGroupIds: [groupId("church-grace-sacraments", "foundations")],
    requiredPriorConcepts: ["grace", "Baptism", "discipleship", "communion"], classifications: ["doctrine", "discipline", "theological_opinion"],
    graphCategories: [], reviewRisk: "high",
    lessonTopics: ["Beatitude, Freedom, and the Call to Holiness", "Prayer as Covenant and Communion", "Object, Intention, Circumstances, Virtue, and Conscience", "Forms, Traditions, and Schools of Prayer", "The Beatitudes, Commandments, and New Law", "Jesus Teaches His Disciples to Pray", "Is Catholic Morality Rule-Based or Repressive?", "Why Pray If God Already Knows?", "A Christ-Centred Rule of Life", "Moral Discernment and Daily Prayer"],
  }),

  subject({
    id: "divine-attributes", name: "God and Divine Attributes", programmeId: "dogma-sacraments", order: 1,
    description: "Studies divine simplicity, eternity, immutability, omniscience, omnipotence, goodness, love, freedom, and providence.",
    difficulty: "advanced", requiredPriorConcepts: ["classical theism", "analogy", "creation"],
    classifications: ["dogma", "doctrine", "theological_opinion", "philosophical_claim"], graphCategories: ["trinity", "secular"], reviewRisk: "high",
    sources: [S.scripture, S.catechism, S.council, S.fathers, S.doctors, S.catholicScholarship],
    lessonTopics: ["The God Who Is", "Divine Simplicity and Perfection", "Univocal, Equivocal, and Analogical Language", "Eternity, Immutability, Impassibility, and Living Love", "Biblical Names and Attributes of God", "Lateran IV, Vatican I, and Classical Theism", "Does Simplicity Make God Empty or Impersonal?", "Can an Immutable God Answer Prayer?", "Speaking Truly but Not Comprehensively about God", "Adoration before the Mystery of God"],
  }),
  subject({
    id: "trinity", name: "Trinity", programmeId: "dogma-sacraments", order: 2,
    description: "Develops a precise biblical, conciliar, patristic, and apologetic account of the one divine nature in three Persons.",
    difficulty: "advanced", prerequisiteGroupIds: [groupId("divine-attributes", "distinctions")],
    requiredPriorConcepts: ["divine nature", "analogy", "person and relation"], classifications: ["dogma", "doctrine", "theological_opinion"],
    graphCategories: ["trinity"], reviewRisk: "critical", traditions: ["Catholic", "Eastern Orthodox", "Protestant", "Islam", "Unitarian movements"],
    lessonTopics: ["The Trinity as the Central Mystery", "The Missions of Son and Spirit", "Nature, Person, Procession, Relation, and Mission", "Generation, Spiration, Appropriation, and Perichoresis", "Trinitarian Patterns across Scripture", "Nicaea, Constantinople, and the Cappadocians", "Is One God in Three Persons Logically Incoherent?", "Is the Trinity a Pagan or Late Invention?", "A Biblical and Conciliar Trinitarian Case", "Prayer to the Father through the Son in the Spirit"],
  }),
  subject({
    id: "christology", name: "Christology", programmeId: "dogma-sacraments", order: 3,
    description: "Studies the identity, two natures, two wills, knowledge, humanity, divinity, and missions of the incarnate Word.",
    difficulty: "advanced", prerequisiteGroupIds: [groupId("trinity", "evidence")],
    requiredPriorConcepts: ["Trinity", "Incarnation", "nature and person"], classifications: ["dogma", "doctrine", "theological_opinion", "historical_claim"],
    graphCategories: ["christology", "historical", "islam"], reviewRisk: "critical",
    traditions: ["Catholic", "Eastern Orthodox", "Oriental Orthodox", "Islam", "Unitarian movements"],
    lessonTopics: ["The Eternal Word Made Flesh", "The Mystery of Christ's Human Life", "Hypostatic Union, Nature, Person, and Communication of Idioms", "Christ's Wills, Knowledge, Freedom, and Sinlessness", "High and Low Christology in the New Testament", "Ephesus, Chalcedon, and Constantinople III", "Did Jesus Claim Divinity?", "Do the Two Natures Divide Christ?", "From Scripture to the Christological Dogmas", "Following the Fully Divine and Fully Human Lord"],
  }),
  subject({
    id: "redemption-resurrection", name: "Redemption and Resurrection", programmeId: "dogma-sacraments", order: 4,
    description: "Integrates the Cross, sacrifice, satisfaction, recapitulation, victory, descent, bodily Resurrection, Ascension, and continuing priesthood of Christ.",
    difficulty: "advanced", prerequisiteGroupIds: [groupId("christology", "evidence")],
    requiredPriorConcepts: ["Incarnation", "covenant sacrifice", "sin and death"], classifications: ["dogma", "doctrine", "theological_opinion", "historical_claim"],
    graphCategories: ["christology", "historical", "islam"], reviewRisk: "critical",
    lessonTopics: ["Why the Cross Saves", "The Bodily Resurrection and Exaltation", "Sacrifice, Satisfaction, Substitution, Recapitulation, and Victory", "Resuscitation, Resurrection, Ascension, and Parousia", "Passion Predictions and Apostolic Kerygma", "Historical Evidence and the Transformation of Easter Faith", "Is Penal Substitution the Whole Gospel?", "Could Resurrection Faith Arise without an Empty Tomb?", "A Multi-Faceted Catholic Account of Redemption", "Dying and Rising with Christ"],
  }),
  subject({
    id: "grace-justification-salvation", name: "Grace, Justification, and Salvation", programmeId: "dogma-sacraments", order: 5,
    description: "Examines original sin, prevenient grace, justification, sanctification, merit, perseverance, predestination, assurance, and final salvation.",
    difficulty: "advanced", prerequisiteGroupIds: [groupId("redemption-resurrection", "synthesis")],
    requiredPriorConcepts: ["redemption", "grace", "faith and charity"], classifications: ["dogma", "doctrine", "theological_opinion"],
    graphCategories: ["protestant"], reviewRisk: "critical", traditions: ["Catholic", "Lutheran", "Reformed", "Wesleyan", "Eastern Orthodox"],
    lessonTopics: ["Grace as God's Free and Transforming Gift", "Justification and New Life in Christ", "Initial Justification, Sanctification, Merit, and Reward", "Predestination, Freedom, Perseverance, and Assurance", "Paul, James, and the Obedience of Faith", "Orange, Trent, Vatican II, and Ecumenical Clarifications", "Do Catholics Teach Salvation by Works?", "Can Salvation Be Lost or Known with Certainty?", "Grace Alone and Faith Working through Love", "Hope, Humility, and Perseverance"],
  }),
  subject({
    id: "sacraments", name: "Sacraments", programmeId: "dogma-sacraments", order: 6,
    description: "Studies sacramentality, institution by Christ, sign and grace, validity, fruitfulness, character, minister, recipient, and the seven sacraments as an ordered whole.",
    difficulty: "advanced", prerequisiteGroupIds: [groupId("grace-justification-salvation", "evidence")],
    requiredPriorConcepts: ["grace", "Church", "Paschal Mystery", "symbol and causality"], classifications: ["dogma", "doctrine", "discipline", "theological_opinion"],
    graphCategories: ["eucharist", "protestant"], reviewRisk: "high", traditions: ["Catholic", "Eastern Orthodox", "Protestant"], cccParts: ["II"],
    lessonTopics: ["Christ the Primordial Sacrament and the Church", "The Seven Sacraments as an Economy", "Sign, Symbol, Cause, Validity, Liceity, and Fruitfulness", "Sacramental Character, Minister, Intention, and Recipient", "Sacramental Patterns in Scripture", "Patristic Practice and Magisterial Definition", "Are Sacraments Unbiblical Ritualism?", "Does Ex Opere Operato Make Faith Irrelevant?", "One Sacramental Economy, Seven Gifts", "Mystagogy and Sacramental Living"],
  }),
  subject({
    id: "eucharist", name: "Eucharist", programmeId: "dogma-sacraments", order: 7,
    description: "Develops the biblical, liturgical, patristic, conciliar, and philosophical account of sacrifice, memorial, Real Presence, transubstantiation, communion, and adoration.",
    difficulty: "advanced", prerequisiteGroupIds: [groupId("sacraments", "distinctions")],
    requiredPriorConcepts: ["sacrament", "sacrifice", "substance and accidents", "Paschal Mystery"], classifications: ["dogma", "doctrine", "discipline"],
    graphCategories: ["eucharist", "protestant"], reviewRisk: "critical", traditions: ["Catholic", "Eastern Orthodox", "Lutheran", "Reformed", "Baptist", "Anglican"], cccParts: ["II"],
    lessonTopics: ["The Eucharist as Source and Summit", "The Mass as Sacrifice, Memorial, Presence, and Banquet", "Presence, Transubstantiation, Sacramental Mode, and Sign", "Sacrifice, Re-Presentation, Repetition, and Participation", "Bread of Life, Last Supper, and Pauline Communion", "Ignatius, Justin, Irenaeus, Trent, and Vatican II", "Is the Eucharist Only Symbolic?", "Does the Mass Repeat Calvary?", "The Cumulative Case for Eucharistic Faith", "Communion, Adoration, and Eucharistic Mission"],
  }),
  subject({
    id: "eschatology", name: "Last Things and Christian Hope", programmeId: "dogma-sacraments", order: 8,
    description: "Covers death, particular judgment, heaven, hell, purgatory, resurrection, final judgment, new creation, and disciplined interpretation of apocalyptic claims.",
    difficulty: "advanced", prerequisiteGroupIds: [groupId("redemption-resurrection", "synthesis"), groupId("grace-justification-salvation", "synthesis")],
    requiredPriorConcepts: ["Resurrection", "grace", "communion of saints"], classifications: ["dogma", "doctrine", "theological_opinion"],
    graphCategories: ["protestant"], reviewRisk: "high", traditions: ["Catholic", "Eastern Orthodox", "Protestant", "Adventist movements"],
    lessonTopics: ["Death, Judgment, and the Hope of Heaven", "Resurrection, Final Judgment, and New Creation", "Particular and Final Judgment; Heaven, Purgatory, and Hell", "Dogma, Apocalyptic Symbol, and Speculative Timelines", "Biblical Witness to Purification and Resurrection", "Councils, Liturgy, and the Communion of Saints", "Is Purgatory a Second Chance or Purchased Salvation?", "Does Eternal Hell Contradict Divine Love?", "A Christ-Centred Account of the Last Things", "Watchfulness, Hope, and Prayer for the Dead"],
  }),

  subject({
    id: "church-authority", name: "Church and Authority", programmeId: "church-tradition", order: 1,
    description: "Studies the Church's divine origin, marks, visibility, communion, indefectibility, teaching authority, mission, and relation to the Kingdom.",
    cccParts: ["I", "II"], classifications: ["dogma", "doctrine", "discipline"], graphCategories: ["papacy", "protestant"], reviewRisk: "critical",
    traditions: ["Catholic", "Eastern Orthodox", "Protestant"],
    lessonTopics: ["The Church Born from the Trinity's Mission", "One, Holy, Catholic, and Apostolic", "Church, Kingdom, Mystical Body, People, and Institution", "Authority, Infallibility, Indefectibility, and Impeccability", "Matthew 16 and 18; Luke 10 and 22; John 20 and 21", "The Church in Acts and the Earliest Fathers", "Did Jesus Found an Institutional Church?", "Does Church Failure Disprove Her Claims?", "A Biblical and Historical Ecclesiology", "Belonging, Mission, and Ecclesial Conversion"],
  }),
  subject({
    id: "apostolic-succession", name: "Apostolic Succession", programmeId: "church-tradition", order: 2,
    description: "Examines apostolic office, episcopacy, ordination, succession, communion, and early testimony to continuity in ministry and teaching.",
    prerequisiteGroupIds: [groupId("church-authority", "evidence")], requiredPriorConcepts: ["apostle", "bishop", "Holy Orders", "Tradition"],
    classifications: ["dogma", "doctrine", "discipline", "historical_claim"], graphCategories: ["papacy", "historical", "protestant"], reviewRisk: "high",
    traditions: ["Catholic", "Eastern Orthodox", "Oriental Orthodox", "Anglican", "Protestant"],
    lessonTopics: ["From Apostolic Mission to Successor Ministry", "Bishops, Presbyters, and Deacons", "Succession of Office, Teaching, Sacrament, and Communion", "Validity, Liceity, Historic Episcopate, and Apostolicity", "Succession Patterns in Acts and the Pastoral Epistles", "Clement, Ignatius, Irenaeus, and Early Lists", "Was Monarchical Episcopacy a Late Invention?", "Is Doctrinal Fidelity Enough without Succession?", "A Cumulative Case for Apostolic Succession", "Receiving and Serving Apostolic Faith"],
  }),
  subject({
    id: "papacy-magisterium", name: "Papacy and Magisterium", programmeId: "church-tradition", order: 3,
    description: "Distinguishes Petrine primacy, papal jurisdiction, infallibility, levels of teaching, assent, collegiality, synodality, and historical development.",
    difficulty: "advanced", prerequisiteGroupIds: [groupId("apostolic-succession", "evidence")],
    requiredPriorConcepts: ["apostolic succession", "primacy", "episcopal college"], classifications: ["dogma", "doctrine", "discipline", "historical_claim"],
    graphCategories: ["papacy", "protestant"], reviewRisk: "critical", traditions: ["Catholic", "Eastern Orthodox", "Anglican", "Protestant"],
    lessonTopics: ["Peter's Ministry and the Bishop of Rome", "The Magisterium in Service of Revelation", "Primacy, Supremacy, Infallibility, Inspiration, and Impeccability", "Extraordinary and Ordinary Teaching; Assent and Prudence", "Keys, Rock, Strengthening, and Shepherding", "Rome in the Fathers, Councils, Vatican I, and Vatican II", "Was Peter Really the Rock?", "Do Bad Popes or Doctrinal Disputes Refute Infallibility?", "Presenting the Petrine Case without Overstatement", "Communion with Peter and the Episcopal College"],
  }),
  subject({
    id: "liturgy", name: "Liturgy", programmeId: "church-tradition", order: 4,
    description: "Studies Christ's priestly action, the liturgical year, rites, signs, active participation, East and West, inculturation, and the relation of worship to doctrine.",
    cccParts: ["II", "IV"], classifications: ["doctrine", "discipline", "theological_opinion", "historical_claim"], graphCategories: ["eucharist", "eastern"], reviewRisk: "high",
    sources: [S.scripture, S.catechism, S.council, S.papal, S.dicastery, S.liturgy, S.history, S.catholicScholarship],
    traditions: ["Latin Catholic", "Eastern Catholic", "Eastern Orthodox", "Anglican", "Protestant"],
    lessonTopics: ["Christ the High Priest of the Liturgy", "The Liturgical Year and the Paschal Mystery", "Liturgy, Devotion, Sacrament, Sacramental, and Rubric", "Active Participation, Inculturation, Organic Development, and Abuse", "Worship in Temple, Synagogue, and New Testament Church", "Rites of East and West through History", "Is Catholic Worship Empty Ritual?", "Did Vatican II Abolish Tradition?", "Lex Orandi, Lex Credendi, Lex Vivendi", "Entering the Church's Prayer"],
  }),
  subject({
    id: "mary", name: "Mary", programmeId: "church-tradition", order: 5,
    description: "Places Marian doctrine within Christology and ecclesiology: divine motherhood, perpetual virginity, Immaculate Conception, Assumption, typology, devotion, and mediation.",
    prerequisiteGroupIds: [groupId("christ-paschal-mystery", "synthesis")], cccParts: ["I", "IV"],
    requiredPriorConcepts: ["Incarnation", "grace", "typology", "communion of saints"], classifications: ["dogma", "doctrine", "discipline", "theological_opinion"],
    graphCategories: ["christology", "protestant", "islam"], reviewRisk: "critical", traditions: ["Catholic", "Eastern Orthodox", "Protestant", "Islam"],
    lessonTopics: ["Mary in the Mystery of Christ and the Church", "The Four Marian Dogmas", "Worship, Veneration, Hyperdulia, Devotion, and Consecration", "Mediation of Christ, Intercession, and Marian Cooperation", "New Eve, Ark, Queen Mother, and Woman of Revelation", "Ephesus, Patristic Witness, and Dogmatic Definitions", "Do Catholics Worship Mary?", "Are the Immaculate Conception and Assumption Unbiblical?", "A Christ-Centred Marian Case", "With Mary, Hearing and Doing the Word"],
  }),
  subject({
    id: "saints-communion", name: "Saints and the Communion of Saints", programmeId: "church-tradition", order: 6,
    description: "Covers holiness, canonisation, heavenly intercession, relics, images, patronage, prayer for the dead, and Christ's unique mediation.",
    prerequisiteGroupIds: [groupId("church-authority", "foundations")], cccParts: ["I", "IV"],
    requiredPriorConcepts: ["Church as communion", "Resurrection", "intercession"], classifications: ["dogma", "doctrine", "discipline", "historical_claim"],
    graphCategories: ["protestant", "eastern"], reviewRisk: "high", traditions: ["Catholic", "Eastern Orthodox", "Protestant"],
    lessonTopics: ["The Communion of Holy Persons and Holy Things", "Saints, Relics, Images, and Canonisation", "Adoration, Veneration, Intercession, Invocation, and Mediation", "Public Cult, Private Devotion, Canonisation, and Theological Opinion", "Heavenly Worship and Intercession in Scripture", "Martyrs, Catacombs, Councils, and Living Tradition", "Why Ask Saints to Pray?", "Are Relics and Images Idolatrous?", "Christ's One Mediation and Shared Intercession", "Friendship with the Saints and the Call to Holiness"],
  }),
  subject({
    id: "church-history", name: "Church History", programmeId: "church-tradition", order: 7, profile: "historical",
    description: "Provides a critical, primary-source-oriented survey from the apostolic age to the present without apologetic whitewashing or hostile reductionism.",
    difficulty: "intermediate", classifications: ["historical_claim", "doctrine", "discipline"], graphCategories: ["historical", "pagan", "protestant"], reviewRisk: "high",
    sources: [S.scripture, S.history, S.council, S.papal, S.fathers, S.academic, S.catholicScholarship],
    traditions: ["Catholic", "Eastern Orthodox", "Oriental Orthodox", "Protestant", "Islam", "secular historiography"],
    lessonTopics: ["Apostolic Age to Imperial Christianity", "Late Antiquity to the Medieval Synthesis", "Primary, Secondary, Confessional, and Polemical Sources", "Development, Corruption, Reform, and Reception", "Councils, Missions, Schisms, and Reform Movements", "Modernity, Global Catholicism, and Vatican II", "Crusades, Inquisitions, and Religious Violence", "Scandals, Colonialism, and the Myth of a Golden Age", "Telling Church History with Truth and Hope", "Learning Repentance, Gratitude, and Fidelity from History"],
  }),
  subject({
    id: "church-fathers", name: "Church Fathers and Doctors", programmeId: "church-tradition", order: 8, profile: "historical",
    description: "Introduces patristic periods, genres, doctrinal controversies, spiritual exegesis, major Fathers and Doctors, and responsible citation.",
    prerequisiteGroupIds: [groupId("church-history", "development")], difficulty: "advanced",
    requiredPriorConcepts: ["apostolic age", "doctrinal development", "primary sources"], classifications: ["historical_claim", "doctrine", "theological_opinion"],
    graphCategories: ["historical", "christology", "trinity"], reviewRisk: "high", traditions: ["Catholic", "Eastern Orthodox", "Oriental Orthodox", "Protestant patristic retrieval"],
    lessonTopics: ["Apostolic Fathers and the Second Century", "Greek, Latin, Syriac, and Desert Traditions", "Genre, Text, Translation, Authenticity, and Context", "Consensus of the Fathers, Individual Opinion, and Development", "Irenaeus, Athanasius, Cappadocians, Chrysostom, and Cyril", "Tertullian, Cyprian, Ambrose, Jerome, Augustine, and Gregory", "Did the Fathers Teach Modern Denominational Systems?", "How Proof-Texting the Fathers Distorts History", "Using Patristic Evidence Responsibly", "Reading the Fathers for Doctrine and Holiness"],
  }),
  subject({
    id: "councils-heresies", name: "Councils and Heresies", programmeId: "church-tradition", order: 9, profile: "historical",
    description: "Maps major ecumenical councils, classical heresies, conciliar authority, canons, reception, and doctrinal development.",
    prerequisiteGroupIds: [groupId("church-fathers", "development"), groupId("church-authority", "distinctions")], difficulty: "advanced",
    requiredPriorConcepts: ["Magisterium", "Fathers", "development of doctrine"], classifications: ["dogma", "doctrine", "discipline", "historical_claim"],
    graphCategories: ["christology", "trinity", "papacy", "historical"], reviewRisk: "critical",
    traditions: ["Catholic", "Eastern Orthodox", "Oriental Orthodox", "Assyrian Church of the East", "Protestant"],
    lessonTopics: ["From Jerusalem to Nicaea and Constantinople", "Ephesus, Chalcedon, and the Later Councils", "Heresy, Schism, Anathema, Canon, Definition, and Reception", "Dogmatic Definition, Disciplinary Canon, and Historical Enforcement", "Arian, Pneumatomachian, Nestorian, and Monophysite Controversies", "Medieval, Tridentine, and Vatican Councils", "Were Councils Political Victories by the Powerful?", "Can Councils Contradict One Another?", "Reading Conciliar Teaching in Context", "Guarding Truth for Communion and Mission"],
  }),

  subject({
    id: "moral-theology", name: "Moral Theology", programmeId: "moral-spiritual", order: 1,
    description: "Develops a Christ-centred account of beatitude, freedom, law, virtue, conscience, moral acts, sin, grace, and prudential judgment.",
    cccParts: ["III"], classifications: ["doctrine", "discipline", "theological_opinion"], graphCategories: ["secular"], reviewRisk: "critical",
    sources: [S.scripture, S.catechism, S.council, S.papal, S.dicastery, S.doctors, S.catholicScholarship],
    traditions: ["Catholic", "Eastern Orthodox", "Protestant", "secular ethical theories"],
    lessonTopics: ["Beatitude and Life in Christ", "Freedom, Grace, Law, and Virtue", "Object, Intention, Circumstances, and Consequences", "Intrinsic Evil, Cooperation, Double Effect, and Prudence", "Beatitudes, Decalogue, Sermon on the Mount, and Pauline Ethics", "Natural Law and the Moral Magisterium", "Is Catholic Morality Legalistic?", "Can Conscience Override Moral Truth?", "From Moral Norm to Virtuous Discipleship", "Examination, Conversion, and Growth in Charity"],
  }),
  subject({
    id: "conscience-virtue-sin", name: "Conscience, Virtue, and Sin", programmeId: "moral-spiritual", order: 2,
    description: "Examines conscience formation, cardinal and theological virtues, passions, habits, mortal and venial sin, culpability, scandal, and conversion.",
    prerequisiteGroupIds: [groupId("moral-theology", "distinctions")], cccParts: ["III"],
    requiredPriorConcepts: ["moral act", "natural law", "grace"], classifications: ["doctrine", "theological_opinion"], graphCategories: ["secular"], reviewRisk: "high",
    lessonTopics: ["Conscience as Judgment of Practical Reason", "Virtue, Vice, Passion, Habit, and Grace", "Mortal, Venial, Grave Matter, Knowledge, and Consent", "Formal and Material Cooperation; Scandal and Remote Effects", "Biblical Conversion and the New Heart", "Aquinas, the Catechism, and Formation of Conscience", "Is Following Conscience Always Enough?", "Does Sin Language Produce Scrupulosity or Shame?", "Truthful Conscience and Merciful Conversion", "A Sustainable Practice of Examination"],
  }),
  subject({
    id: "life-bioethics", name: "Human Life and Bioethics", programmeId: "moral-spiritual", order: 3,
    description: "Applies human dignity, natural law, ordinary and extraordinary care, double effect, and solidarity to life, medicine, technology, and death.",
    difficulty: "advanced", prerequisiteGroupIds: [groupId("moral-theology", "evidence")], cccParts: ["III"],
    requiredPriorConcepts: ["human dignity", "moral object", "double effect", "cooperation"], classifications: ["doctrine", "discipline", "theological_opinion", "scientific_claim"],
    graphCategories: ["secular"], reviewRisk: "critical", traditions: ["Catholic", "secular bioethics", "other Christian bioethics"],
    sources: [S.scripture, S.catechism, S.papal, S.dicastery, S.catholicScholarship, S.academic, S.science],
    lessonTopics: ["The Inviolable Dignity of Human Life", "Medicine as Service to the Whole Person", "Killing, Letting Die, Ordinary Care, and Proportionate Treatment", "Embryo, Foetus, Patient, Personhood, and Bodily Integrity", "Scripture, Incarnation, and the Least of These", "Evangelium Vitae and Catholic Healthcare Ethics", "Abortion, Euthanasia, and the Hard Cases", "IVF, Gene Editing, Brain Death, and Emerging Technology", "Reasoning from Dignity without Slogans", "Accompaniment, Care, and Public Witness"],
  }),
  subject({
    id: "marriage-sexuality-family", name: "Marriage, Sexuality, and Family", programmeId: "moral-spiritual", order: 4,
    description: "Studies creation, embodiment, chastity, marriage, celibacy, fertility, family, sexual ethics, pastoral accompaniment, and contested anthropologies.",
    difficulty: "advanced", prerequisiteGroupIds: [groupId("moral-theology", "evidence")], cccParts: ["II", "III"],
    requiredPriorConcepts: ["human dignity", "sacrament", "virtue", "moral act"], classifications: ["dogma", "doctrine", "discipline", "theological_opinion", "scientific_claim"],
    graphCategories: ["secular", "protestant"], reviewRisk: "critical", traditions: ["Catholic", "Eastern Orthodox", "Protestant", "secular gender and sexual theories"],
    sources: [S.scripture, S.catechism, S.council, S.papal, S.dicastery, S.catholicScholarship, S.academic, S.science],
    lessonTopics: ["Created Male and Female for Gift and Communion", "Marriage as Covenant and Sacrament", "Chastity, Celibacy, Continence, and Abstinence", "Validity, Nullity, Divorce, Separation, and Pastoral Accompaniment", "Jesus, Paul, and the Biblical Theology of the Body", "Humanae Vitae, Familiaris Consortio, and Amoris Laetitia", "Contraception, Infertility, and Responsible Parenthood", "Same-Sex Attraction, Gender Dysphoria, and Pastoral Truth", "Explaining Catholic Sexual Ethics as a Whole", "Family Prayer, Fidelity, and Merciful Accompaniment"],
  }),
  subject({
    id: "prayer-spiritual-life", name: "Prayer and Spiritual Life", programmeId: "moral-spiritual", order: 5,
    description: "Deepens vocal, meditative, contemplative, liturgical, biblical, and devotional prayer within discernment, asceticism, sacramental life, and charity.",
    cccParts: ["IV"], classifications: ["doctrine", "discipline", "theological_opinion", "historical_claim"], graphCategories: ["eastern"], reviewRisk: "medium",
    sources: [S.scripture, S.catechism, S.liturgy, S.fathers, S.doctors, S.catholicScholarship],
    traditions: ["Latin Catholic spiritual schools", "Eastern Catholic spiritual schools", "Eastern Orthodox spirituality"],
    lessonTopics: ["Prayer as Gift, Covenant, and Communion", "The Lord's Prayer and the Prayer of Jesus", "Vocal, Meditative, Contemplative, Liturgical, and Devotional Prayer", "Consolation, Desolation, Dryness, Distraction, and Discernment", "Psalms, Gospels, and Lectio Divina", "Desert, Benedictine, Carmelite, Ignatian, and Salesian Traditions", "Why Pray to Saints or Use Repeated Prayers?", "How to Discern Extraordinary Spiritual Claims", "Building an Ecclesial Rule of Prayer", "Prayer Flowing into Sacrament and Charity"],
  }),
  subject({
    id: "catholic-social-teaching", name: "Catholic Social Teaching", programmeId: "moral-spiritual", order: 6,
    description: "Organises human dignity, common good, solidarity, subsidiarity, rights, duties, work, economy, politics, peace, migration, and care for creation.",
    prerequisiteGroupIds: [groupId("moral-theology", "foundations")], cccParts: ["III"],
    requiredPriorConcepts: ["human dignity", "common good", "virtue and law"], classifications: ["doctrine", "discipline", "theological_opinion", "historical_claim"],
    graphCategories: ["secular"], reviewRisk: "critical", traditions: ["Catholic", "liberal", "conservative", "socialist", "libertarian", "nationalist political traditions"],
    sources: [S.scripture, S.catechism, S.papal, S.dicastery, S.history, S.catholicScholarship, S.academic],
    lessonTopics: ["Dignity, Common Good, Solidarity, and Subsidiarity", "The Universal Destination of Goods and Preferential Love for the Poor", "Principle, Prudential Judgment, Policy, and Party Platform", "Rights, Duties, Authority, Civil Disobedience, and Cooperation", "Prophets, Jubilee, Acts, and the Works of Mercy", "Rerum Novarum to Laudato Si' and Fratelli Tutti", "Is Catholic Social Teaching Left-Wing or Right-Wing?", "War, Migration, Markets, Welfare, and Environmental Disputes", "Applying Principles without Partisan Capture", "Social Friendship and the Works of Mercy"],
  }),

  subject({
    id: "philosophy-logic", name: "Philosophy and Logic", programmeId: "reason-culture", order: 1,
    description: "Builds conceptual analysis, metaphysics, epistemology, logic, argument mapping, fallacy recognition, and the Catholic relation to philosophical schools.",
    classifications: ["philosophical_claim", "theological_opinion"], graphCategories: ["secular"], reviewRisk: "medium",
    sources: [S.papal, S.doctors, S.catholicScholarship, S.academic], traditions: ["Aristotelian-Thomist", "Augustinian", "analytic", "continental", "secular philosophical traditions"], cccParts: ["I", "III"],
    lessonTopics: ["Why Faith Needs Philosophy", "Reality, Knowledge, Truth, and Goodness", "Term, Proposition, Inference, Validity, Soundness, and Probability", "Essence, Existence, Substance, Accident, Cause, and Relation", "Reading and Mapping Arguments", "Catholic Engagement with Major Philosophical Traditions", "Do Fallacies Automatically Disprove Conclusions?", "Is Metaphysics Obsolete?", "Reasoning Clearly about Theological Claims", "Intellectual Virtue and Love of Truth"],
  }),
  subject({
    id: "natural-theology", name: "Natural Theology", programmeId: "reason-culture", order: 2,
    description: "Studies what reason can know about God through contingency, causality, intelligibility, morality, consciousness, order, and religious experience.",
    difficulty: "advanced", prerequisiteGroupIds: [groupId("philosophy-logic", "distinctions")],
    requiredPriorConcepts: ["validity and soundness", "causality", "analogy", "metaphysics"], classifications: ["doctrine", "philosophical_claim", "theological_opinion", "scientific_claim"],
    graphCategories: ["secular"], reviewRisk: "high", traditions: ["classical theism", "atheism", "agnosticism", "deism", "pantheism"],
    sources: [S.scripture, S.catechism, S.council, S.papal, S.doctors, S.catholicScholarship, S.academic, S.science],
    lessonTopics: ["What Natural Reason Can Know of God", "The Grammar of Classical Theism", "Cosmological, Teleological, Moral, and Experiential Arguments", "Proof, Demonstration, Inference, Probability, and Cumulative Case", "Romans 1, Wisdom, and the Created Order", "Aquinas, Vatican I, and Contemporary Arguments", "Who Caused God?", "Do Quantum Physics or Multiverses Remove the Need for God?", "A Modest Cumulative Case for Theism", "Reason Opening into Worship"],
  }),
  subject({
    id: "problem-evil", name: "Problem of Evil and Suffering", programmeId: "reason-culture", order: 3,
    description: "Treats logical, evidential, existential, pastoral, natural, and moral evil through freedom, providence, Cross, resurrection, and eschatological hope.",
    difficulty: "advanced", prerequisiteGroupIds: [groupId("natural-theology", "evidence")],
    requiredPriorConcepts: ["divine attributes", "freedom", "providence", "probability"], classifications: ["doctrine", "theological_opinion", "philosophical_claim", "historical_claim"],
    graphCategories: ["secular"], reviewRisk: "critical", traditions: ["Catholic", "atheist", "skeptical", "other Christian theodicies"],
    sources: [S.scripture, S.catechism, S.papal, S.fathers, S.doctors, S.catholicScholarship, S.academic],
    lessonTopics: ["Naming Evil without Minimising Suffering", "The Cross and the Hope of Resurrection", "Logical, Evidential, Existential, Moral, and Natural Evil", "Defence, Theodicy, Mystery, Permission, and Causation", "Job, Lament, Jesus, and the Suffering Church", "Augustine, Aquinas, and Modern Responses", "Could an All-Good God Permit This World?", "Does Heaven Justify Horrendous Suffering?", "A Philosophical and Christological Response", "Presence, Lament, Action, and Hope"],
  }),
  subject({
    id: "faith-science", name: "Faith and Science", programmeId: "reason-culture", order: 4,
    description: "Distinguishes methods and limits of theology, philosophy, and empirical science while treating cosmology, evolution, human origins, miracles, and technology.",
    difficulty: "advanced", prerequisiteGroupIds: [groupId("philosophy-logic", "evidence")],
    requiredPriorConcepts: ["levels of explanation", "causality", "genre", "scientific method"], classifications: ["doctrine", "theological_opinion", "historical_claim", "philosophical_claim", "scientific_claim"],
    graphCategories: ["secular", "historical"], reviewRisk: "critical", traditions: ["Catholic", "scientific naturalism", "young-earth creationism", "intelligent design", "evolutionary creation"],
    sources: [S.scripture, S.catechism, S.papal, S.dicastery, S.history, S.catholicScholarship, S.academic, S.science],
    lessonTopics: ["One Truth, Distinct Disciplines", "Creation and the Scientific Account of Nature", "Methodological and Metaphysical Naturalism", "Creation, Evolution, Providence, Chance, and Design", "Genesis, Wisdom, and Biblical Cosmology", "Galileo, Darwin, Big Bang Cosmology, and Catholic Scientists", "Has Science Disproved God?", "Can Catholics Accept Evolution and Common Ancestry?", "Integrating Theology, Philosophy, and Science", "Scientific Vocation and Moral Responsibility"],
  }),
  subject({
    id: "atheism-secularism", name: "Atheism and Secularism", programmeId: "reason-culture", order: 5,
    description: "Engages philosophical atheism, agnosticism, naturalism, humanism, secularisation, religious trauma, moral critique, and lived unbelief.",
    difficulty: "advanced", prerequisiteGroupIds: [groupId("natural-theology", "evidence"), groupId("problem-evil", "objections")],
    requiredPriorConcepts: ["natural theology", "problem of evil", "epistemic humility"], classifications: ["doctrine", "historical_claim", "philosophical_claim", "scientific_claim"],
    graphCategories: ["secular"], reviewRisk: "high", traditions: ["atheism", "agnosticism", "secular humanism", "naturalism", "post-Christian spirituality"],
    sources: [S.catechism, S.council, S.papal, S.history, S.catholicScholarship, S.academic, S.comparative, S.science],
    lessonTopics: ["Varieties of Unbelief", "The Secular Age and Lived Atheism", "Atheism, Agnosticism, Naturalism, Humanism, and Indifference", "Intellectual Objection, Moral Protest, Trauma, and Social Identity", "Biblical Encounters with Idolatry and Practical Godlessness", "Modern Critics and Catholic Responses", "Can Morality and Meaning Exist without God?", "Is Religion Harmful Wish-Fulfilment?", "Dialogue with the Honest Unbeliever", "Witness, Repentance, Beauty, and Friendship"],
  }),
  subject({
    id: "debate-source-evaluation", name: "Debate, Reasoning, and Source Evaluation", programmeId: "reason-culture", order: 6,
    description: "Trains argument analysis, research, citation verification, source hierarchy, comparative fairness, rhetoric, dialogue, and misinformation resistance.",
    prerequisiteGroupIds: [groupId("philosophy-logic", "distinctions")], cccParts: ["I", "III"],
    requiredPriorConcepts: ["argument structure", "doctrinal classification", "primary and secondary sources"], classifications: ["historical_claim", "philosophical_claim", "scientific_claim", "theological_opinion"],
    graphCategories: ["secular", "protestant", "islam"], reviewRisk: "medium", traditions: ["all comparative traditions as applicable"],
    sources: [S.catechism, S.council, S.history, S.catholicScholarship, S.academic, S.comparative, S.science],
    lessonTopics: ["Apologetics as an Act of Charity", "Questions, Claims, Evidence, and Burdens of Proof", "Primary, Secondary, Tertiary, Official, and Polemical Sources", "Quote, Paraphrase, Context, Translation, Licence, and Uncertainty", "Building Argument Maps and Evidence Tables", "Verifying Documents, Paragraphs, Canons, and URLs", "Steel-Manning the Strongest Objection", "Responding to Gish Gallops, Memes, and Misinformation", "A Reproducible Apologetics Research Method", "Truthful Speech, Gentleness, and Intellectual Repentance"],
  }),

  subject({
    id: "protestant-controversies", name: "Protestant Controversies", programmeId: "comparative-apologetics", order: 1,
    description: "Maps Protestant diversity and treats authority, justification, sacraments, ecclesiology, Mary, saints, assurance, and worship using confessional sources.",
    difficulty: "advanced", classifications: ["dogma", "doctrine", "discipline", "historical_claim", "theological_opinion"],
    graphCategories: ["protestant", "canon", "papacy", "eucharist"], reviewRisk: "critical",
    traditions: ["Lutheran", "Reformed", "Anglican", "Methodist", "Baptist", "Pentecostal", "non-denominational Evangelical", "Adventist"],
    sources: [S.scripture, S.catechism, S.council, S.fathers, S.history, S.catholicScholarship, S.academic, S.comparative],
    lessonTopics: ["The Reformations and Protestant Families", "Shared Christianity and Real Divisions", "Sola Scriptura, Prima Scriptura, Tradition, and Confession", "Justification, Sacrament, Church, and Assurance across Traditions", "Key Biblical Disputes in Context", "Confessions, Reformers, Trent, and Ecumenical Dialogues", "Did Catholic Corruption Make the Reformation Necessary?", "Are Catholic Distinctives Additions to the Gospel?", "Constructing Tradition-Specific Catholic Responses", "Dialogue, Cooperation, and the Work for Unity"],
  }),
  subject({
    id: "eastern-orthodox-relations", name: "Eastern Orthodox Relations", programmeId: "comparative-apologetics", order: 2,
    description: "Treats shared apostolic faith, primacy, synodality, Filioque, councils, divorce, purgatory, development, Eastern Catholicism, and reunion.",
    difficulty: "expert", prerequisiteGroupIds: [groupId("councils-heresies", "development")],
    requiredPriorConcepts: ["ecumenical councils", "papal primacy", "Trinity", "liturgy"], classifications: ["dogma", "doctrine", "discipline", "historical_claim", "theological_opinion"],
    graphCategories: ["eastern", "papacy", "trinity"], reviewRisk: "critical", traditions: ["Catholic", "Eastern Orthodox", "Eastern Catholic", "Oriental Orthodox where distinguished"],
    sources: [S.scripture, S.catechism, S.council, S.papal, S.fathers, S.liturgy, S.history, S.catholicScholarship, S.academic, S.comparative],
    lessonTopics: ["Sister Churches and the Wound of Division", "Rome, Constantinople, and the First Millennium", "Primacy, Synodality, Supremacy, and Universal Jurisdiction", "Filioque: Doctrine, Formula, Language, and Reception", "Biblical and Patristic Models of Communion", "Schism, Councils, Union Attempts, and Modern Dialogue", "Did Rome Invent Papal Supremacy?", "Do Filioque and Later Dogmas Block Reunion?", "A Catholic Case Oriented toward Communion", "Prayer, Humility, and Receptive Ecumenism"],
  }),
  subject({
    id: "islam-christianity", name: "Islam and Christianity", programmeId: "comparative-apologetics", order: 3,
    description: "Introduces Islamic diversity and primary sources before treating God, Trinity, Christ, Crucifixion, Scripture, prophecy, salvation, and dialogue.",
    difficulty: "advanced", prerequisiteGroupIds: [groupId("christ-paschal-mystery", "synthesis")],
    requiredPriorConcepts: ["Trinity", "Christology", "revelation", "canon"], classifications: ["dogma", "doctrine", "historical_claim", "theological_opinion"],
    graphCategories: ["islam", "trinity", "christology", "canon", "historical"], reviewRisk: "critical", traditions: ["Sunni Islam", "Shia Islam", "Ahmadiyya where distinguished", "Catholic"],
    sources: [S.scripture, S.catechism, S.council, S.papal, S.dicastery, S.history, S.catholicScholarship, S.academic, S.comparative],
    lessonTopics: ["Islamic Origins, Beliefs, and Internal Diversity", "Catholic Teaching about Muslims", "Tawhid, Trinity, Incarnation, and Sonship", "Qur'an, Hadith, Tafsir, Sira, and Legal-Theological Schools", "Biblical Witness to Christ and the Cross", "Qur'anic Claims and Early Christian Historical Evidence", "Is the Trinity Shirk or Three Gods?", "Were the Gospels Corrupted and Jesus Not Crucified?", "A Primary-Source Christian-Muslim Dialogue", "Respect, Religious Freedom, and Witness to Christ"],
  }),
  subject({
    id: "judaism-christianity", name: "Judaism and Christianity", programmeId: "comparative-apologetics", order: 4,
    description: "Studies covenant, Israel, Messiah, Torah, Temple, rabbinic development, Christian fulfilment, supersessionist errors, antisemitism, and dialogue.",
    difficulty: "advanced", prerequisiteGroupIds: [groupId("salvation-history", "synthesis")],
    requiredPriorConcepts: ["covenant", "Israel", "Messiah", "typology"], classifications: ["dogma", "doctrine", "historical_claim", "theological_opinion"],
    graphCategories: ["judaism", "canon", "christology", "historical"], reviewRisk: "critical", traditions: ["Rabbinic Judaism", "Orthodox Judaism", "Conservative Judaism", "Reform Judaism", "Catholic"],
    sources: [S.scripture, S.catechism, S.council, S.papal, S.dicastery, S.history, S.catholicScholarship, S.academic, S.comparative],
    lessonTopics: ["Israel, Covenant, and the Jewish Roots of Christianity", "Second Temple and Rabbinic Judaism", "Fulfilment, Continuity, Discontinuity, and Supersessionism", "Messianic Prophecy, Typology, and Retrospective Reading", "Torah, Prophets, Wisdom, and New Testament Claims", "Temple's Fall, Rabbinic Sources, Fathers, and Nostra Aetate", "Did Christians Misread Jewish Scripture?", "Has the Church Replaced or Rejected Israel?", "A Non-Coercive Catholic-Jewish Account", "Repentance for Antisemitism and Shared Moral Witness"],
  }),
  subject({
    id: "world-religions", name: "Other Religions", programmeId: "comparative-apologetics", order: 5,
    description: "Builds a Catholic framework for Hindu, Buddhist, Sikh, indigenous, Chinese, and other religious traditions without collapsing their internal diversity.",
    difficulty: "advanced", classifications: ["doctrine", "historical_claim", "philosophical_claim", "theological_opinion"], graphCategories: ["eastern", "pagan"], reviewRisk: "critical",
    traditions: ["Hindu traditions", "Buddhist traditions", "Sikhism", "Chinese religions", "indigenous religions", "Bahá'í Faith"],
    sources: [S.catechism, S.council, S.papal, S.dicastery, S.history, S.catholicScholarship, S.academic, S.comparative],
    lessonTopics: ["A Catholic Theology of Religions", "Mapping Religious Families without Flattening Them", "Revelation, Religion, Culture, Salvation, and Seeds of the Word", "Monotheism, Non-Dualism, Polytheism, Non-Theism, and Ancestral Traditions", "Biblical Encounters with Nations and Religions", "Nostra Aetate, Mission Documents, and Comparative Scholarship", "Are All Religions Equally True Paths?", "Is Christian Mission Inherently Disrespectful?", "Comparison through Specific Claims and Primary Sources", "Dialogue, Mission, Freedom, and the Common Good"],
  }),
  subject({
    id: "new-religious-movements", name: "New Religious Movements", programmeId: "comparative-apologetics", order: 6,
    description: "Examines restorationist, esoteric, syncretic, high-control, and new revelation movements using their official sources and careful pastoral distinctions.",
    difficulty: "advanced", classifications: ["doctrine", "historical_claim", "philosophical_claim", "theological_opinion"], graphCategories: ["protestant", "pagan", "eastern"], reviewRisk: "critical",
    traditions: ["Latter-day Saints", "Jehovah's Witnesses", "Christian Science", "New Age movements", "high-control religious groups", "modern esoteric movements"],
    sources: [S.scripture, S.catechism, S.history, S.catholicScholarship, S.academic, S.comparative],
    lessonTopics: ["What Counts as a New Religious Movement?", "Restoration, New Revelation, and Charismatic Founders", "Heresy, Schism, Sect, Cult, Denomination, and High Control", "Official Doctrine, Lived Practice, Former-Member Testimony, and Polemic", "Testing Prophecy and Claims about Christ", "Movement Scriptures, Histories, and Organisational Sources", "How Should Catholics Evaluate New Revelation?", "How Can We Help without Dehumanising Members?", "A Claim-by-Claim Discernment Method", "Pastoral Care, Boundaries, and Patient Witness"],
  }),

  subject({
    id: "apologist-lab", name: "Apologist Lab", programmeId: "apologist-lab", order: 1, profile: "lab",
    description: "Capstone studios for research briefs, sourced cases, dialogues, timed answers, live-quiz explanations, and post-performance review.",
    difficulty: "advanced", prerequisiteGroupIds: [groupId("debate-source-evaluation", "synthesis")],
    requiredPriorConcepts: ["source hierarchy", "argument mapping", "comparative fairness", "doctrinal classification"],
    classifications: ["dogma", "doctrine", "discipline", "theological_opinion", "historical_claim", "philosophical_claim", "scientific_claim"],
    graphCategories: GRAPH_CATEGORIES, reviewRisk: "critical", traditions: ["selected according to case"],
    sources: Object.values(S), expertChallenge: false,
    lessonTopics: ["Briefing a Real Apologetics Question", "Defining Audience, Claim, and Burden", "Building a Verified Primary-Source Dossier", "Creating a Citation and Licensing Audit", "Constructing the Positive Catholic Case", "Preparing Rebuttal, Cross-Questions, and Concessions", "Simulated One-to-One Dialogue", "Live Quiz and Timed Audience Questions", "Accuracy, Charity, and Rhetoric Debrief", "Mastery Portfolio and Reviewer Submission"],
  }),
  subject({
    id: "expert-challenges", name: "Optional Expert Challenges", programmeId: "apologist-lab", order: 2, profile: "lab",
    description: "Optional high-risk interdisciplinary cases requiring multi-tradition sources, historical method, philosophical precision, and accountable expert review.",
    difficulty: "expert", prerequisiteGroupIds: [groupId("apologist-lab", "debrief")],
    requiredPriorConcepts: ["advanced doctrinal synthesis", "primary-source verification", "live dialogue"],
    classifications: DOCTRINAL_CLASSIFICATIONS, graphCategories: GRAPH_CATEGORIES, reviewRisk: "critical",
    traditions: ["multiple traditions according to challenge"], sources: Object.values(S), optional: true, expertChallenge: true, liveQuizEligible: false,
    lessonTopics: ["Choosing a Boundary Case without Sensationalism", "Writing the Expert Review Charter", "Triangulating Multilingual and Contested Sources", "Recording Uncertainty, Minority Views, and Licence Limits", "Constructing a Multi-Disciplinary Position Paper", "Red-Team Review by Theology, History, and Subject Specialists", "Formal Debate before an Expert Panel", "Hostile-Question Simulation and Pastoral Reframing", "Publishing a Corrections and Limitations Memo", "Final Defence before Independent Reviewers"],
  }),
];

export const programmeDefinitions = [
  {
    id: "core-foundation", name: "Compulsory Catholic Foundation Route", slug: "compulsory-catholic-foundation-route", order: 1,
    description: "A Christ-centred entry route through revelation, Scripture, salvation history, Trinity, Christ, Church, grace, sacraments, moral life, and prayer before specialist branching.",
    audience: coreAudience, difficulty: "foundation-to-intermediate", prerequisiteGroupIds: [], unlockCondition: { type: "always" },
    subjectIds: ["catholic-foundations", "revelation-faith", "scripture-canon", "salvation-history", "god-trinity-creation", "christ-paschal-mystery", "church-grace-sacraments", "moral-prayer-foundations"],
    outcomes: ["Give a coherent Christ-centred account of Catholic faith", "Navigate the Catechism's Creed, Sacraments, Moral Life, and Prayer", "Distinguish doctrinal authority levels", "Use Scripture, Tradition, and Magisterium together", "Enter specialist tracks with the required prior concepts"],
  },
  {
    id: "dogma-sacraments", name: "Dogma and Sacramental Theology", slug: "dogma-and-sacramental-theology", order: 2,
    description: "Advanced parallel study of God, Trinity, Christ, redemption, grace, sacraments, Eucharist, and Christian hope.",
    audience: specialistAudience, difficulty: "intermediate-to-advanced", prerequisiteGroupIds: [groupId("moral-prayer-foundations", "synthesis")],
    subjectIds: ["divine-attributes", "trinity", "christology", "redemption-resurrection", "grace-justification-salvation", "sacraments", "eucharist", "eschatology"],
    outcomes: ["Explain central dogmas with technical precision", "Integrate biblical, patristic, conciliar, and philosophical evidence", "Answer major sacramental and salvation disputes", "Relate doctrine to liturgy and spiritual life"],
  },
  {
    id: "church-tradition", name: "Church, Tradition, and History", slug: "church-tradition-and-history", order: 3,
    description: "Parallel specialist formation in ecclesiology, succession, papacy, liturgy, Mary, saints, history, Fathers, councils, and heresies.",
    audience: specialistAudience, difficulty: "intermediate-to-expert", prerequisiteGroupIds: [groupId("moral-prayer-foundations", "synthesis")],
    subjectIds: ["church-authority", "apostolic-succession", "papacy-magisterium", "liturgy", "mary", "saints-communion", "church-history", "church-fathers", "councils-heresies"],
    outcomes: ["Explain the Church's visible and spiritual constitution", "Use early and conciliar sources responsibly", "Distinguish development from corruption", "Address authority and Marian disputes without overstatement"],
  },
  {
    id: "moral-spiritual", name: "Moral and Spiritual Formation", slug: "moral-and-spiritual-formation", order: 4,
    description: "Parallel formation in moral reasoning, conscience, virtue, bioethics, marriage, prayer, spiritual traditions, and Catholic social teaching.",
    audience: specialistAudience, difficulty: "intermediate-to-advanced", prerequisiteGroupIds: [groupId("moral-prayer-foundations", "synthesis")],
    subjectIds: ["moral-theology", "conscience-virtue-sin", "life-bioethics", "marriage-sexuality-family", "prayer-spiritual-life", "catholic-social-teaching"],
    outcomes: ["Reason from beatitude, dignity, virtue, and moral object", "Form conscience within truth and grace", "Apply principles to contested cases with pastoral care", "Develop a stable sacramental and prayer life"],
  },
  {
    id: "reason-culture", name: "Reason, Philosophy, and Contemporary Culture", slug: "reason-philosophy-and-contemporary-culture", order: 5,
    description: "Parallel formation in philosophy, natural theology, evil, science, secularism, debate, and source evaluation.",
    audience: scholarlyAudience, difficulty: "intermediate-to-advanced", prerequisiteGroupIds: [groupId("moral-prayer-foundations", "synthesis")],
    subjectIds: ["philosophy-logic", "natural-theology", "problem-evil", "faith-science", "atheism-secularism", "debate-source-evaluation"],
    outcomes: ["Construct valid and proportionate arguments", "Distinguish philosophical, theological, historical, and scientific claims", "Engage unbelief and suffering honestly", "Verify sources and communicate uncertainty"],
  },
  {
    id: "comparative-apologetics", name: "Comparative Apologetics", slug: "comparative-apologetics", order: 6,
    description: "Tradition-specific comparison with Protestant, Orthodox, Jewish, Islamic, world-religion, and new-religious-movement claims.",
    audience: scholarlyAudience, difficulty: "advanced-to-expert", prerequisiteGroupIds: [groupId("moral-prayer-foundations", "synthesis")],
    subjectIds: ["protestant-controversies", "eastern-orthodox-relations", "islam-christianity", "judaism-christianity", "world-religions", "new-religious-movements"],
    outcomes: ["Describe other traditions from their recognised sources", "Distinguish internal variations", "Build claim-specific Catholic responses", "Practise dialogue ordered to truth, freedom, and charity"],
  },
  {
    id: "apologist-lab", name: "Apologist Lab and Expert Challenges", slug: "apologist-lab-and-expert-challenges", order: 7,
    description: "Performance-based capstones for verified research, case construction, live explanation, dialogue, peer review, and expert challenge work.",
    audience: ["apologists", "catechists", "advanced learners", "live-quiz presenters"], difficulty: "advanced-to-expert", prerequisiteGroupIds: [groupId("debate-source-evaluation", "synthesis")],
    subjectIds: ["apologist-lab", "expert-challenges"],
    outcomes: ["Produce a source-audited apologetic case", "Perform under time and audience constraints", "Receive and act on independent review", "Record limitations, corrections, and unresolved issues"],
  },
  {
    id: "bible-books", name: "Independent Bible-Book Studies", slug: "independent-bible-book-studies", order: 8,
    description: "Seventy-three independent Catholic book tracks with canonical context, literary structure, theology, difficult texts, and Christological-ecclesial synthesis.",
    audience: ["beginners with Scripture foundations", "Bible-study groups", "catechists", "apologists", "advanced learners"], difficulty: "foundation-to-advanced",
    prerequisiteGroupIds: [groupId("scripture-canon", "distinctions")], subjectIds: [],
    outcomes: ["Read every biblical book within the Catholic canon", "Respect genre, historical setting, and literary structure", "Relate each book to Christ and the Church without arbitrary proof-texting", "Address difficult texts and apologetic disputes responsibly"],
  },
];

const books = [
  ["genesis", "Genesis", "Old Testament", "Pentateuch", "creation, covenant, patriarchs, sin, promise, and providence", "critical"],
  ["exodus", "Exodus", "Old Testament", "Pentateuch", "deliverance, Passover, covenant, law, tabernacle, and divine presence", "high"],
  ["leviticus", "Leviticus", "Old Testament", "Pentateuch", "holiness, sacrifice, priesthood, purity, atonement, and worship", "high"],
  ["numbers", "Numbers", "Old Testament", "Pentateuch", "wilderness testing, rebellion, priesthood, guidance, and promise", "high"],
  ["deuteronomy", "Deuteronomy", "Old Testament", "Pentateuch", "covenant renewal, law, love, memory, land, and choice", "high"],
  ["joshua", "Joshua", "Old Testament", "Historical Books", "land, covenant fidelity, conquest, rest, and inheritance", "critical"],
  ["judges", "Judges", "Old Testament", "Historical Books", "apostasy, deliverance, violence, kingship, and covenant disorder", "critical"],
  ["ruth", "Ruth", "Old Testament", "Historical Books", "loyalty, providence, kinship, redemption, and Davidic lineage", "medium"],
  ["1-samuel", "1 Samuel", "Old Testament", "Historical Books", "prophecy, kingship, Saul, David, obedience, and anointing", "high"],
  ["2-samuel", "2 Samuel", "Old Testament", "Historical Books", "Davidic covenant, kingship, sin, judgment, mercy, and succession", "high"],
  ["1-kings", "1 Kings", "Old Testament", "Historical Books", "Solomon, temple, divided kingdom, prophecy, and idolatry", "high"],
  ["2-kings", "2 Kings", "Old Testament", "Historical Books", "prophets, reform, exile, judgment, and remnant", "high"],
  ["1-chronicles", "1 Chronicles", "Old Testament", "Historical Books", "genealogy, David, worship, priesthood, and temple preparation", "medium"],
  ["2-chronicles", "2 Chronicles", "Old Testament", "Historical Books", "temple, kings, reform, judgment, exile, and restoration", "medium"],
  ["ezra", "Ezra", "Old Testament", "Historical Books", "return, temple, Torah, identity, repentance, and restoration", "high"],
  ["nehemiah", "Nehemiah", "Old Testament", "Historical Books", "rebuilding, leadership, covenant renewal, justice, and community", "medium"],
  ["tobit", "Tobit", "Old Testament", "Deuterocanonical Historical Books", "family fidelity, almsgiving, angels, marriage, healing, and providence", "high"],
  ["judith", "Judith", "Old Testament", "Deuterocanonical Historical Books", "courage, prayer, deliverance, typology, and faithful resistance", "high"],
  ["esther", "Esther", "Old Testament", "Historical Books", "providence, courage, diaspora, reversal, intercession, and deliverance", "high"],
  ["1-maccabees", "1 Maccabees", "Old Testament", "Deuterocanonical Historical Books", "persecution, covenant fidelity, resistance, temple, and political complexity", "high"],
  ["2-maccabees", "2 Maccabees", "Old Testament", "Deuterocanonical Historical Books", "martyrdom, resurrection, intercession, prayer for the dead, and temple", "critical"],
  ["job", "Job", "Old Testament", "Wisdom Books", "innocent suffering, wisdom, protest, divine freedom, and encounter", "critical"],
  ["psalms", "Psalms", "Old Testament", "Wisdom Books", "praise, lament, kingship, Torah, temple, Messiah, and prayer", "high"],
  ["proverbs", "Proverbs", "Old Testament", "Wisdom Books", "wisdom, virtue, speech, work, family, justice, and fear of the Lord", "medium"],
  ["ecclesiastes", "Ecclesiastes", "Old Testament", "Wisdom Books", "vanity, mortality, work, joy, wisdom, and judgment", "high"],
  ["song-of-songs", "Song of Songs", "Old Testament", "Wisdom Books", "human love, desire, covenant, allegory, Israel, Christ, and Church", "high"],
  ["wisdom", "Wisdom", "Old Testament", "Deuterocanonical Wisdom Books", "wisdom, righteousness, immortality, providence, creation, and idolatry", "high"],
  ["sirach", "Sirach", "Old Testament", "Deuterocanonical Wisdom Books", "wisdom, law, worship, friendship, speech, family, and ancestors", "high"],
  ["isaiah", "Isaiah", "Old Testament", "Major Prophets", "holiness, judgment, remnant, servant, Emmanuel, consolation, and new creation", "critical"],
  ["jeremiah", "Jeremiah", "Old Testament", "Major Prophets", "covenant breach, prophetic suffering, judgment, new covenant, and hope", "high"],
  ["lamentations", "Lamentations", "Old Testament", "Major Prophets", "catastrophe, lament, justice, mercy, memory, and hope", "high"],
  ["baruch", "Baruch", "Old Testament", "Deuterocanonical Prophetic Books", "exile, repentance, wisdom, consolation, and Jerusalem", "high"],
  ["ezekiel", "Ezekiel", "Old Testament", "Major Prophets", "glory, judgment, responsibility, new heart, resurrection, temple, and shepherd", "critical"],
  ["daniel", "Daniel", "Old Testament", "Major Prophets", "faithful witness, kingdoms, apocalyptic, Son of Man, resurrection, and deliverance", "critical"],
  ["hosea", "Hosea", "Old Testament", "Minor Prophets", "covenant love, infidelity, judgment, mercy, and restoration", "high"],
  ["joel", "Joel", "Old Testament", "Minor Prophets", "day of the Lord, repentance, Spirit, judgment, and restoration", "high"],
  ["amos", "Amos", "Old Testament", "Minor Prophets", "justice, worship, judgment, remnant, and restoration", "high"],
  ["obadiah", "Obadiah", "Old Testament", "Minor Prophets", "Edom, pride, violence, judgment, and the Lord's kingdom", "medium"],
  ["jonah", "Jonah", "Old Testament", "Minor Prophets", "mission, mercy, repentance, enemy love, and prophetic resistance", "high"],
  ["micah", "Micah", "Old Testament", "Minor Prophets", "justice, judgment, Bethlehem, remnant, shepherd, and mercy", "high"],
  ["nahum", "Nahum", "Old Testament", "Minor Prophets", "Nineveh, oppression, divine justice, violence, and consolation", "critical"],
  ["habakkuk", "Habakkuk", "Old Testament", "Minor Prophets", "violence, complaint, faith, judgment, and rejoicing", "high"],
  ["zephaniah", "Zephaniah", "Old Testament", "Minor Prophets", "day of the Lord, remnant, purification, judgment, and joy", "high"],
  ["haggai", "Haggai", "Old Testament", "Minor Prophets", "temple rebuilding, priorities, holiness, presence, and hope", "medium"],
  ["zechariah", "Zechariah", "Old Testament", "Minor Prophets", "visions, temple, priest and king, shepherd, Messiah, and restoration", "critical"],
  ["malachi", "Malachi", "Old Testament", "Minor Prophets", "covenant, priesthood, marriage, sacrifice, messenger, and day of the Lord", "high"],
  ["matthew", "Matthew", "New Testament", "Gospels", "Jesus as Messiah, kingdom, Torah fulfilment, Church, discipleship, and mission", "critical"],
  ["mark", "Mark", "New Testament", "Gospels", "Jesus as Son, kingdom, authority, suffering Messiah, discipleship, and Cross", "critical"],
  ["luke", "Luke", "New Testament", "Gospels", "salvation, Spirit, mercy, prayer, poor, women, journey, and universal mission", "critical"],
  ["john", "John", "New Testament", "Gospels", "Word, signs, belief, life, glory, sacramentality, Spirit, and communion", "critical"],
  ["acts", "Acts of the Apostles", "New Testament", "Apostolic History", "Spirit, mission, Church, apostolic authority, councils, witness, and Gentiles", "critical"],
  ["romans", "Romans", "New Testament", "Pauline Letters", "Gospel, sin, justification, faith, grace, Israel, Spirit, ethics, and unity", "critical"],
  ["1-corinthians", "1 Corinthians", "New Testament", "Pauline Letters", "Church unity, holiness, Eucharist, gifts, love, and resurrection", "critical"],
  ["2-corinthians", "2 Corinthians", "New Testament", "Pauline Letters", "apostolic ministry, weakness, reconciliation, generosity, and new covenant", "high"],
  ["galatians", "Galatians", "New Testament", "Pauline Letters", "justification, faith, law, promise, freedom, Spirit, and new creation", "critical"],
  ["ephesians", "Ephesians", "New Testament", "Pauline Letters", "Church, unity, grace, mystery, new humanity, marriage, and spiritual warfare", "high"],
  ["philippians", "Philippians", "New Testament", "Pauline Letters", "Christ's humility, joy, partnership, suffering, citizenship, and perseverance", "high"],
  ["colossians", "Colossians", "New Testament", "Pauline Letters", "Christ's supremacy, creation, Church, reconciliation, baptism, and new life", "critical"],
  ["1-thessalonians", "1 Thessalonians", "New Testament", "Pauline Letters", "conversion, holiness, love, resurrection, parousia, and encouragement", "high"],
  ["2-thessalonians", "2 Thessalonians", "New Testament", "Pauline Letters", "perseverance, judgment, lawlessness, parousia, tradition, and work", "critical"],
  ["1-timothy", "1 Timothy", "New Testament", "Pastoral Letters", "Church order, doctrine, ministry, worship, widows, wealth, and witness", "high"],
  ["2-timothy", "2 Timothy", "New Testament", "Pastoral Letters", "apostolic deposit, Scripture, suffering, ministry, perseverance, and succession", "high"],
  ["titus", "Titus", "New Testament", "Pastoral Letters", "elders, sound doctrine, grace, good works, order, and mission", "high"],
  ["philemon", "Philemon", "New Testament", "Pauline Letters", "reconciliation, brotherhood, slavery, persuasion, and Christian communion", "high"],
  ["hebrews", "Hebrews", "New Testament", "Catholic and Pauline-associated Letters", "Christ's priesthood, covenant, sacrifice, sanctuary, faith, perseverance, and worship", "critical"],
  ["james", "James", "New Testament", "Catholic Letters", "trials, wisdom, works, speech, partiality, anointing, and prayer", "critical"],
  ["1-peter", "1 Peter", "New Testament", "Catholic Letters", "living hope, holiness, suffering, priestly people, witness, and shepherding", "high"],
  ["2-peter", "2 Peter", "New Testament", "Catholic Letters", "divine power, transfiguration, prophecy, false teaching, parousia, and canon", "critical"],
  ["1-john", "1 John", "New Testament", "Catholic Letters", "Incarnation, fellowship, truth, love, sin, anointing, and assurance", "critical"],
  ["2-john", "2 John", "New Testament", "Catholic Letters", "truth, love, commandment, Incarnation, hospitality, and false teaching", "high"],
  ["3-john", "3 John", "New Testament", "Catholic Letters", "truth, hospitality, authority conflict, mission, and imitation", "medium"],
  ["jude", "Jude", "New Testament", "Catholic Letters", "contending for faith, false teachers, judgment traditions, mercy, and perseverance", "critical"],
  ["revelation", "Revelation", "New Testament", "Apocalyptic and Prophetic Literature", "worship, witness, Lamb, empire, judgment, martyrs, new creation, and hope", "critical"],
];

export const bibleBookDefinitions = books.map(([id, name, testament, section, themes, reviewRisk], index) => Object.freeze({
  id: "bible." + id,
  name,
  programmeId: "bible-books",
  order: index + 1,
  description: "An independent Catholic study of " + name + " focused on " + themes + ".",
  profile: "bible",
  audience: ["Bible-study beginners", "formed Catholics", "catechists", "apologists"],
  difficulty: reviewRisk === "critical" ? "intermediate-to-advanced" : "foundation-to-intermediate",
  classifications: ["doctrine", "historical_claim", "theological_opinion"],
  sources: [S.scripture, S.catechism, S.council, S.fathers, S.liturgy, S.catholicScholarship, S.academic],
  traditions: section.includes("Deuterocanonical") ? ["Catholic", "Eastern Orthodox", "Protestant canon traditions"] : [],
  graphCategories: ["canon"].concat(["Gospels", "Apostolic History", "Pauline Letters", "Catholic Letters", "Apocalyptic and Prophetic Literature"].includes(section) ? ["christology", "historical"] : []),
  reviewRisk,
  cccParts: ["I"],
  prerequisiteGroupIds: [groupId("scripture-canon", "distinctions")],
  requiredPriorConcepts: ["inspiration", "canon", "genre", "salvation history"],
  optional: true,
  expertChallenge: false,
  liveQuizEligible: true,
  testament,
  canonicalSection: section,
  themes,
  lessonTopics: [
    name + ": Canonical and Historical Setting",
    name + ": Literary Map and Major Movements",
    name + ": " + themes,
    name + ": Difficult Texts and Interpretive Questions",
    name + " in Christ, the Church, Liturgy, and Christian Life",
  ],
}));

programmeDefinitions.find((programme) => programme.id === "bible-books").subjectIds = bibleBookDefinitions.map((book) => book.id);

export const routeDefinitions = [
  {
    id: "route.convert", name: "Convert or Catechumen Route", audience: "inquirers, catechumens, and recent converts",
    requiredProgrammeIds: ["core-foundation"], recommendedSubjectIds: ["eucharist", "papacy-magisterium", "mary", "grace-justification-salvation", "liturgy"],
    rule: "Complete the compulsory route in order, then branch according to catechetical needs and local formation.",
  },
  {
    id: "route.catholic", name: "Catholic Deepening Route", audience: "practising and returning Catholics",
    requiredProgrammeIds: ["core-foundation"], recommendedSubjectIds: ["prayer-spiritual-life", "moral-theology", "liturgy", "catholic-social-teaching", "church-history"],
    rule: "Use a diagnostic to recognise prior formation, but require mastery evidence before skipping a core group.",
  },
  {
    id: "route.apologist", name: "Apologist Route", audience: "catechists, evangelists, and apologists",
    requiredProgrammeIds: ["core-foundation", "reason-culture", "apologist-lab"], recommendedSubjectIds: ["protestant-controversies", "islam-christianity", "papacy-magisterium", "eucharist", "natural-theology"],
    rule: "Complete foundations, source evaluation, one comparative specialism, and the independently reviewed Apologist Lab.",
  },
  {
    id: "route.casual-quiz", name: "Casual Quiz Route", audience: "casual and live-quiz players",
    requiredProgrammeIds: [], recommendedSubjectIds: ["catholic-foundations", "salvation-history", "christ-paschal-mystery"],
    rule: "Permit practice-only previews after the first foundations group; previews do not confer mastery or unlock advanced doctrinal production.",
  },
  {
    id: "route.bible-reader", name: "Independent Bible-Book Route", audience: "individuals and parish Bible groups",
    requiredProgrammeIds: [], recommendedSubjectIds: bibleBookDefinitions.map((book) => book.id),
    rule: "After Scripture and Canon distinctions, choose any biblical book independently; no book requires completion of another book.",
  },
];

export const disputeCoverage = [
  ["revelation-authority", "Scripture, Tradition, and Magisterium", ["revelation-faith", "scripture-canon", "church-authority"]],
  ["biblical-canon", "Catholic canon and deuterocanonical books", ["scripture-canon", "bible.tobit", "bible.judith", "bible.wisdom", "bible.sirach", "bible.baruch", "bible.1-maccabees", "bible.2-maccabees"]],
  ["trinity", "Trinity and divine unity", ["god-trinity-creation", "divine-attributes", "trinity", "islam-christianity"]],
  ["christ-divinity", "Divinity and humanity of Christ", ["christ-paschal-mystery", "christology", "islam-christianity"]],
  ["resurrection", "Historical Resurrection", ["christ-paschal-mystery", "redemption-resurrection", "atheism-secularism"]],
  ["atonement", "Atonement models and sacrifice", ["redemption-resurrection", "eucharist"]],
  ["justification", "Grace, faith, works, merit, and assurance", ["church-grace-sacraments", "grace-justification-salvation", "protestant-controversies"]],
  ["baptism", "Baptismal regeneration and infant Baptism", ["sacraments", "protestant-controversies"]],
  ["eucharist", "Real Presence and Eucharistic sacrifice", ["eucharist", "protestant-controversies", "liturgy"]],
  ["confession", "Sacramental confession and priestly absolution", ["sacraments", "apostolic-succession", "protestant-controversies"]],
  ["apostolic-succession", "Apostolic succession and episcopacy", ["church-authority", "apostolic-succession", "church-fathers"]],
  ["papacy", "Petrine primacy, jurisdiction, and infallibility", ["papacy-magisterium", "eastern-orthodox-relations", "protestant-controversies"]],
  ["mary", "Marian dogmas and devotion", ["mary", "christology", "protestant-controversies"]],
  ["saints-images", "Saints, intercession, relics, and images", ["saints-communion", "protestant-controversies", "eastern-orthodox-relations"]],
  ["purgatory", "Purgatory and prayer for the dead", ["eschatology", "saints-communion", "bible.2-maccabees"]],
  ["filioque", "Filioque and Trinitarian procession", ["trinity", "eastern-orthodox-relations", "councils-heresies"]],
  ["development", "Development of doctrine versus corruption", ["church-history", "church-fathers", "councils-heresies"]],
  ["evil", "Logical and evidential problems of evil", ["problem-evil", "natural-theology"]],
  ["science", "Creation, evolution, cosmology, and miracles", ["faith-science", "natural-theology", "bible.genesis"]],
  ["atheism", "God, morality, meaning, and religious harm", ["atheism-secularism", "natural-theology", "problem-evil"]],
  ["sexual-ethics", "Marriage, sexuality, gender, and contraception", ["marriage-sexuality-family", "moral-theology"]],
  ["bioethics", "Abortion, euthanasia, reproduction, and biotechnology", ["life-bioethics", "moral-theology"]],
  ["social-teaching", "Economics, politics, war, migration, and ecology", ["catholic-social-teaching"]],
  ["islam", "Trinity, Incarnation, Crucifixion, and Gospel integrity in Islam", ["islam-christianity", "trinity", "christology", "redemption-resurrection", "scripture-canon"]],
  ["religions", "Uniqueness of Christ, salvation, and interreligious dialogue", ["world-religions", "new-religious-movements", "christology"]],
].map(([id, name, subjectIds]) => ({ id: "dispute." + id, name, subjectIds }));

export const explicitGapRegister = [
  {
    id: "gap.graph-taxonomy", severity: "high", owner: "Apologia Graph",
    description: "The current graph taxonomy has no dedicated categories for sacraments generally, moral theology, prayer, liturgy, social teaching, bioethics, Church Fathers, councils, or most biblical books.",
    disposition: "Keep empty or nearest-category links in draft; require graph-taxonomy approval before lesson production.",
  },
  {
    id: "gap.scripture-licensing", severity: "critical", owner: "Legal and editorial governance",
    description: "No repository policy identifies approved Bible translations, quotation limits, territories, or APK/offline redistribution terms.",
    disposition: "Phase 4 must store references and original paraphrases until a written licensing policy is approved.",
  },
  {
    id: "gap.lesson-block-schema", severity: "critical", owner: "Platform and editorial governance",
    description: "The existing editorial workflow validates quiz Question records, not the complete structured lesson-block model assumed by Phase 4.",
    disposition: "Approve and implement the lesson block schema and revision workflow before full lesson bodies are imported.",
  },
  {
    id: "gap.comparative-reviewers", severity: "critical", owner: "Editorial governance",
    description: "Named qualified reviewers for Orthodox, Islamic, Jewish, world-religion, NRM, science, bioethics, and abuse-sensitive material are not yet assigned.",
    disposition: "Assign reviewers and escalation rules before those lesson batches move beyond draft.",
  },
  {
    id: "gap.source-languages", severity: "medium", owner: "Editorial research",
    description: "The blueprint does not presume staff competence in Greek, Hebrew, Latin, Syriac, Arabic, or other source languages.",
    disposition: "Record translation editions and require specialist review when an argument turns on original-language claims.",
  },
];

export { groupId };
