const heading = (text) => ({ type: "heading", level: 2, text });
const paragraph = (text, sourceIds = []) => ({ type: "paragraph", text, ...(sourceIds.length ? { sourceIds } : {}) });
const scripture = (reference, paraphrase, sourceId) => ({
  type: "scripture_card",
  reference,
  paraphrase,
  sourceId,
  quotationIncluded: false,
});
const magisterial = (locator, summary, sourceId = "src.ccc.main") => ({
  type: "catechism_card",
  locator,
  summary,
  sourceId,
  quotationIncluded: false,
});
const distinctions = (caption, rows) => ({
  type: "distinction_table",
  caption,
  columns: ["Term", "Meaning", "Why it matters"],
  rows,
});
const historical = (relevance, items = []) => ({ relevance, items });
const reference = (sourceId, locator, use) => ({ sourceId, locator, use });

export const catholicFoundationsLessons = [
  {
    phase3LessonId: "les.catholic-foundations.foundations.01",
    centralQuestion: "What is the centre that gives unity and proportion to the whole Catholic faith?",
    learningObjectives: [
      "State the Gospel as the good news of the triune God's saving work in Jesus Christ.",
      "Explain why the Paschal Mystery is central without reducing Catholic faith to one isolated slogan.",
      "Relate conversion, Baptism, discipleship, the Church, and final hope to Christ's saving work.",
    ],
    shortDirectAnswer: "The centre of Catholic faith is Jesus Christ, the eternal Son sent by the Father, crucified and risen for our salvation, who gives the Holy Spirit and gathers us into his life. Every doctrine, sacrament, moral demand, and prayer is understood in relation to this triune saving mystery.",
    fullExplanation: [
      heading("A person and saving event, not a detached formula"),
      paragraph("Christianity begins with what God has done, not with a catalogue of Catholic peculiarities. The Father sends the Son; the Son truly enters human history, dies, rises, and reigns; the Holy Spirit makes Christ's saving work present and forms a people who live toward resurrection. The Gospel is therefore both an announcement and a summons: receive God's gift in faith, conversion, Baptism, worship, and a transformed life.", ["src.scripture.1-corinthians-15", "src.scripture.matthew-28", "src.jp2.catechesi-tradendae"]),
      heading("The Paschal Mystery orders the rest"),
      paragraph("Paul identifies Christ's death, burial, resurrection, and appearances as matters of first importance. Luke presents the risen Christ as the key to the Scriptures and the source of the Church's mission. This priority does not make creation, the Trinity, the Incarnation, the Church, sacraments, morality, or prayer optional. It shows their living connection: the one God creates and promises; the Son assumes human nature and accomplishes redemption; the Spirit joins believers to Christ; and the Church hands on, celebrates, and embodies this gift.", ["src.scripture.1-corinthians-15", "src.scripture.luke-24", "src.ccc.main"]),
      heading("Christ remains the subject of catechesis"),
      paragraph("Catholic catechesis is not finally about the teacher's ideas or victory in an argument. Its subject is Christ and its aim is communion with him. A well-formed apologist therefore asks of every explanation: Does this reveal Christ truthfully, preserve the shape of the whole faith, and invite a free response to grace?", ["src.jp2.catechesi-tradendae", "src.francis.evangelii-gaudium"]),
    ],
    essentialTerminology: [
      { term: "Gospel", definition: "The good news of God's definitive saving action in Jesus Christ, proclaimed for faith, conversion, and new life.", sourceIds: ["src.scripture.1-corinthians-15", "src.ccc.main"] },
      { term: "Paschal Mystery", definition: "Christ's saving Passion, death, Resurrection, and glorification, understood as one redemptive mystery.", sourceIds: ["src.ccc.main"] },
      { term: "Kerygma", definition: "The foundational apostolic proclamation of Jesus Christ and God's saving work in him.", sourceIds: ["src.francis.evangelii-gaudium"] },
      { term: "Conversion", definition: "The grace-enabled turning of mind, heart, and life toward God in response to the Gospel.", sourceIds: ["src.scripture.luke-24", "src.ccc.main"] },
    ],
    scriptureEvidence: [
      scripture("1 Corinthians 15:1-5", "Paul reminds the Corinthians of the Gospel they received and handed on, placing Christ's death, burial, resurrection, and appearances at its core.", "src.scripture.1-corinthians-15"),
      scripture("Luke 24:25-49", "The risen Jesus interprets the Scriptures around his suffering and glory, then commissions witnesses to announce repentance and forgiveness.", "src.scripture.luke-24"),
      scripture("Matthew 28:18-20", "The risen Lord sends the apostles to make disciples through Baptism and teaching, in the name of the Father, Son, and Holy Spirit.", "src.scripture.matthew-28"),
    ],
    catechismMagisterialEvidence: [
      magisterial("CCC 422-429", "The Catechism begins its treatment of Christ by presenting the transmission of Christian faith as the proclamation of Jesus Christ and communion with him."),
      magisterial("CCC 571-573", "The Catechism places Christ's Passion and Resurrection at the centre of the Good News handed on by the apostles."),
      magisterial("Catechesi Tradendae 5-6", "John Paul II teaches that catechesis has Christ himself as its primary subject and seeks communion with him.", "src.jp2.catechesi-tradendae"),
      magisterial("Evangelii Gaudium 34-39", "Francis calls proclamation to preserve proportion and the hierarchy among truths, keeping the saving centre visible.", "src.francis.evangelii-gaudium"),
    ],
    patristicHistoricalEvidence: historical("Early Christian teachers defended the apostolic proclamation as a received whole, not a private reconstruction.", [
      { summary: "Irenaeus appeals to the public apostolic tradition of the churches when defending the rule of faith against rival systems.", sourceId: "src.irenaeus.against-heresies", locator: "Against Heresies III.3" },
    ]),
    importantDistinctions: [
      distinctions("Keeping the Gospel central without shrinking it", [
        ["Centre", "The triune God's saving work in the incarnate, crucified, and risen Christ", "Provides the reference point for every other teaching"],
        ["Whole", "The full deposit of faith and the life that flows from it", "Prevents a slogan from replacing Creed, sacraments, morality, and prayer"],
        ["Response", "Faith, conversion, sacramental incorporation, discipleship, and hope", "Shows that grace creates a lived communion, not mere information"],
      ]),
    ],
    strongObjection: "Catholicism seems to bury the simple Gospel beneath institutions, devotions, moral rules, and disputed doctrines.",
    opposingPosition: "The concern protects the priority of Christ's saving work and warns that religious practices can obscure rather than reveal him when presented as an unranked list. It is strongest when Catholic explanations fail to connect a practice to the Gospel. The objection by itself does not specify a complete alternative account of Church, sacraments, and authority.",
    catholicResponse: "The concern identifies a real catechetical danger, but not an intrinsic defect in Catholic faith. Catholic teaching insists on a centre and a hierarchy of truths. The Church, sacraments, moral life, and prayer are not rival gospels; rightly understood, they are gifts and consequences of the triune saving mystery. Catholics should correct cluttered presentation while refusing to separate Christ from the body, worship, and discipleship he establishes.",
    commonMistakes: [
      "Defining the Gospel only as an individual decision and omitting the Father, the Holy Spirit, the Church, and resurrection hope.",
      "Beginning an explanation of Catholicism with a secondary controversy instead of Christ.",
      "Treating central truths as the only truths that matter.",
      "Speaking as if apologetic skill, rather than grace, produces faith.",
    ],
    practicalSpiritualApplication: "Pray slowly through the events named in 1 Corinthians 15:1-5. Then explain one Catholic practice by completing the sentence, 'This belongs to Christian life because Christ…'. If the connection is unclear, mark the question for further study rather than improvising.",
    summary: "Catholic faith is one coherent response to the Father who saves through the incarnate, crucified, and risen Son and gives the Holy Spirit. Christ and the Paschal Mystery are the centre; the rest of Catholic teaching unfolds their meaning and fruit without becoming optional.",
    reviewPrompts: [
      "Why is the Gospel more than a detached formula?",
      "How can a truth be central without making other doctrines optional?",
      "Give one example of connecting a sacrament or moral teaching to the Paschal Mystery.",
    ],
    practiceIntents: [
      ["multiple_choice", "Identify the most complete Christ-centred description of the Gospel."],
      ["short_response", "Connect one major area of Catholic life to the Paschal Mystery."],
    ],
    references: [
      reference("src.scripture.1-corinthians-15", "1 Corinthians 15:1-5", "Apostolic summary and order of importance"),
      reference("src.scripture.luke-24", "Luke 24:25-49", "Christological reading and missionary commission"),
      reference("src.scripture.matthew-28", "Matthew 28:18-20", "Trinitarian mission, Baptism, and teaching"),
      reference("src.ccc.main", "CCC 422-429; 571-573", "Christ and the Paschal Mystery at the heart of proclamation"),
      reference("src.jp2.catechesi-tradendae", "Sections 5-6", "Christocentric purpose of catechesis"),
      reference("src.francis.evangelii-gaudium", "Sections 34-39", "Doctrinal proportion and Gospel centre"),
      reference("src.irenaeus.against-heresies", "Book III, chapter 3", "Public apostolic transmission"),
    ],
    relatedLessonIds: ["les.catholic-foundations.foundations.02", "les.catholic-foundations.synthesis.01", "les.christology.foundations.01"],
    graphCategoryIds: ["christology", "trinity", "historical"],
    doctrinalClassifications: ["dogma", "doctrine", "historical_claim"],
    comparativeTraditions: [],
  },
  {
    phase3LessonId: "les.catholic-foundations.foundations.02",
    centralQuestion: "Why does the Catechism organize Catholic formation around Creed, sacraments, moral life, and prayer?",
    learningObjectives: [
      "Name the Catechism's four parts and describe the question each part answers.",
      "Explain how profession, celebration, life in Christ, and prayer form one movement rather than four unrelated courses.",
      "Use the four-part pattern to diagnose an unbalanced account of Catholic life.",
    ],
    shortDirectAnswer: "The four parts express one Christian life: the faith the Church professes, the mystery she celebrates, the life grace enables, and the prayer by which believers live in communion with God. Christ unites all four.",
    fullExplanation: [
      heading("One mystery, four inseparable dimensions"),
      paragraph("The Catechism's architecture follows a classic catechetical pattern. Part One asks what the Church believes; Part Two how the saving mystery is celebrated; Part Three how the baptized live in Christ; and Part Four how Christians pray. These are not departments competing for attention. The God confessed in the Creed acts in the liturgy, conforms believers to Christ, and draws them into prayer.", ["src.ccc.main"]),
      heading("The pattern is visible in the apostolic community"),
      paragraph("Acts presents the first believers persevering in apostolic teaching, common life, the breaking of bread, and prayers. Paul likewise joins the indwelling word of Christ, worshipful gratitude, and concrete virtue. These passages do not reproduce the later table of contents, but they show why Christian formation cannot be reduced to information alone.", ["src.scripture.acts-2", "src.scripture.colossians-3"]),
      heading("A diagnostic for curriculum and discipleship"),
      paragraph("The four parts provide a practical balance test. Belief without worship can become abstraction. Worship without truth can lose its object. Moral instruction without grace becomes moralism. Prayer detached from the Church's faith can become self-designed spirituality. A healthy curriculum repeatedly reconnects the four around Christ.", ["src.ccc.main", "src.vatican2.sacrosanctum-concilium"]),
    ],
    essentialTerminology: [
      { term: "Creed", definition: "The Church's ordered profession of the faith received from the apostles.", sourceIds: ["src.ccc.main"] },
      { term: "Sacramental economy", definition: "The communication of the fruits of Christ's Paschal Mystery in the Church's sacramental life.", sourceIds: ["src.ccc.main"] },
      { term: "Life in Christ", definition: "The moral and spiritual life made possible by grace and ordered to beatitude and charity.", sourceIds: ["src.ccc.main"] },
      { term: "Christian prayer", definition: "A living relationship with the triune God, learned and lived in Christ and the Holy Spirit.", sourceIds: ["src.ccc.main"] },
    ],
    scriptureEvidence: [
      scripture("Acts 2:37-47", "The apostolic community responds in conversion and Baptism, then perseveres in apostolic teaching, fellowship, the breaking of bread, and prayers.", "src.scripture.acts-2"),
      scripture("Colossians 3:12-17", "Paul unites Christ-shaped virtues, mutual instruction, worship, gratitude, and daily action in the Lord's name.", "src.scripture.colossians-3"),
      scripture("Romans 12:1-2", "Christian worship includes the offering of embodied life and the renewal of the mind for discernment.", "src.scripture.romans-12"),
    ],
    catechismMagisterialEvidence: [
      magisterial("CCC 13-17", "The Catechism's prologue explains its four-part arrangement: profession of faith, sacraments of faith, life of faith, and prayer in the life of faith."),
      magisterial("CCC 1066-1068", "The opening of Part Two links liturgy to the Paschal Mystery confessed in the Creed."),
      magisterial("CCC 1691-1698", "The opening synthesis of Part Three presents Christian morality as life in Christ and catechesis in the Holy Spirit."),
      magisterial("CCC 2558-2565", "The opening of Part Four describes prayer as covenant and communion with God."),
      magisterial("Sacrosanctum Concilium 10", "The council describes liturgy as the high point toward which the Church's activity is directed and the source from which her power flows.", "src.vatican2.sacrosanctum-concilium"),
    ],
    patristicHistoricalEvidence: historical("Early catechetical practice commonly joined teaching, moral preparation, sacramental initiation, and prayer.", [
      { summary: "The Didache combines moral formation, baptismal instruction, prayer, Eucharistic practice, and community order in one early Christian manual.", sourceId: "src.didache", locator: "Didache 1-4; 7-10; 14" },
      { summary: "Cyril's Jerusalem catecheses prepare candidates through instruction and conversion for sacramental initiation into the Church's confessed faith.", sourceId: "src.cyril.catechetical-lectures", locator: "Procatechesis; Catechetical Lecture 5" },
    ]),
    importantDistinctions: [
      distinctions("The four parts as mutually dependent dimensions", [
        ["Creed", "What the Church believes about God's saving work", "Supplies the truth confessed in worship and life"],
        ["Sacraments", "How Christ's mystery is celebrated and communicated", "Makes formation ecclesial and grace-centred"],
        ["Moral life", "How grace bears fruit in freedom, virtue, and charity", "Prevents belief from remaining merely verbal"],
        ["Prayer", "How believers receive and respond to God in communion", "Keeps every part relational and doxological"],
      ]),
    ],
    strongObjection: "The Catechism's four-part outline is an artificial filing system imposed on the more fluid life of the New Testament.",
    opposingPosition: "This objection rightly observes that the New Testament is not arranged as a modern systematic manual and that no outline can exhaust Christian life. It warns against mistaking a teaching aid for revelation itself.",
    catholicResponse: "The four-part structure is a catechetical synthesis, not a claim that the biblical books use the same table of contents. Its value lies in preserving biblical dimensions that appear together: confession, sacramental communion, transformed conduct, and prayer. The structure serves the mystery; it does not replace Scripture or the lived Church.",
    commonMistakes: [
      "Treating the four parts as independent modules with no common centre.",
      "Equating moral life with earning grace.",
      "Reducing sacraments to ceremonies or prayer to private feeling.",
      "Using the Catechism as a quotation warehouse instead of following its argument and cross-references.",
    ],
    practicalSpiritualApplication: "Audit one week of Catholic life under four headings: what you professed, celebrated, practiced, and prayed. Identify the weakest connection and choose one small action that reconnects it to Christ.",
    summary: "The Catechism's four parts form a single symphony: the mystery confessed in the Creed is celebrated in the sacraments, lived by grace, and received and answered in prayer. The pattern protects formation from becoming merely intellectual, ritual, moralistic, or individualistic.",
    reviewPrompts: [
      "What question does each part of the Catechism answer?",
      "Why is moral life placed after the sacramental economy?",
      "Give one example of imbalance that the four-part pattern can expose.",
    ],
    practiceIntents: [
      ["multiple_choice", "Match each Catechism part to its governing question."],
      ["scenario", "Diagnose which dimension is missing from a one-sided formation plan."],
    ],
    references: [
      reference("src.scripture.acts-2", "Acts 2:37-47", "Apostolic teaching, sacramental life, fellowship, and prayer"),
      reference("src.scripture.colossians-3", "Colossians 3:12-17", "Doctrine, virtue, worship, and action held together"),
      reference("src.scripture.romans-12", "Romans 12:1-2", "Embodied worship and moral transformation"),
      reference("src.ccc.main", "CCC 13-17; 1066-1068; 1691-1698; 2558-2565", "Four-part architecture and its internal unity"),
      reference("src.vatican2.sacrosanctum-concilium", "Section 10", "Liturgy as summit and source"),
      reference("src.didache", "Chapters 1-4; 7-10; 14", "Early integration of teaching, life, sacraments, and prayer"),
      reference("src.cyril.catechetical-lectures", "Procatechesis; Catechetical Lecture 5", "Integrated catechumenal formation"),
    ],
    relatedLessonIds: ["les.catholic-foundations.foundations.01", "les.catholic-foundations.evidence.02", "les.liturgy.foundations.01"],
    graphCategoryIds: ["christology", "historical"],
    doctrinalClassifications: ["doctrine", "discipline", "historical_claim"],
    comparativeTraditions: [],
  },
  {
    phase3LessonId: "les.catholic-foundations.distinctions.01",
    centralQuestion: "How should Catholics distinguish dogma, doctrine, discipline, theological opinion, and historical claim?",
    learningObjectives: [
      "Define five common claim categories without treating them as interchangeable.",
      "Explain why authority, object, and required assent must be examined before evaluating a Catholic claim.",
      "Classify representative examples cautiously and identify when expert review is needed.",
    ],
    shortDirectAnswer: "Dogma is divinely revealed truth definitively proposed by the Church; doctrine is the broader body of authoritative teaching; discipline regulates ecclesial life; theological opinion is a reasoned but non-definitive proposal; and a historical claim concerns contingent events assessed through evidence. Confusing these categories produces false contradictions and exaggerated certainty.",
    fullExplanation: [
      heading("Begin with the kind of claim"),
      paragraph("The word 'Catholic' can describe teachings of very different authority, changeable laws, common customs, schools of theology, or claims made by particular historians. Before asking whether a statement is true, obligatory, reformable, or disputed, identify what sort of statement it is and who has made it. The Catechism itself distinguishes dogmas and their organic connection from the Church's disciplines and diverse theological work.", ["src.ccc.interpretation", "src.ccc.main"]),
      heading("Doctrine is broader than dogma"),
      paragraph("Doctrine is a broad term for authoritative Christian teaching. Dogmas are doctrines presented as divinely revealed and definitively binding. Other teachings may be definitive because they are required to guard or expound revelation, while still others are taught authoritatively without being defined irreformably. A beginner need not memorize every canonical formula yet, but must resist the binary mistake that every teaching is either a dogma or merely optional.", ["src.ccc.interpretation"]),
      heading("Practices and explanations require their own tests"),
      paragraph("A discipline can change because pastoral governance responds to circumstances, yet its doctrinal purposes may remain. A theological opinion can be respected without becoming the faith of the Church. A historical claim requires primary sources and historical method; an officeholder's mistake does not automatically falsify a dogma, and a dogmatic definition does not settle every disputed historical detail.", ["src.ccc.main", "src.vatican2.dei-verbum"]),
    ],
    essentialTerminology: [
      { term: "Dogma", definition: "A truth contained in divine revelation and definitively proposed by the Church as divinely revealed, requiring the assent of theological faith.", sourceIds: ["src.ccc.interpretation"] },
      { term: "Doctrine", definition: "Authoritative teaching concerning faith or morals; the term is broader than formally defined dogma.", sourceIds: ["src.ccc.interpretation"] },
      { term: "Discipline", definition: "An ecclesial rule or regulated practice governing Christian and institutional life; it is not identical with the doctrine it may protect or express.", sourceIds: ["src.ccc.main"] },
      { term: "Theological opinion", definition: "A reasoned proposal within theology that has not been definitively taught and may be debated within the bounds of faith.", sourceIds: ["src.ccc.main"] },
      { term: "Historical claim", definition: "A claim about contingent persons, actions, texts, dates, causes, or developments evaluated through historical evidence.", sourceIds: ["src.vatican2.dei-verbum"] },
    ],
    scriptureEvidence: [
      scripture("1 Timothy 3:14-15", "Paul describes the Church with a truth-bearing role while instructing Timothy about ordered conduct within the household of God.", "src.scripture.1-timothy-3"),
      scripture("Ephesians 4:11-16", "The Church's ministries serve unity in faith, maturity, and stability so believers are not driven by every new teaching.", "src.scripture.ephesians-4"),
      scripture("Acts 2:42", "The earliest Jerusalem community perseveres in the apostles' teaching as well as common and sacramental life.", "src.scripture.acts-2"),
    ],
    catechismMagisterialEvidence: [
      magisterial("CCC 84-87", "The apostolic deposit is entrusted to the whole Church, with an authentic teaching office serving the Word of God.", "src.ccc.interpretation"),
      magisterial("CCC 88-90", "The Catechism describes dogmas and emphasizes their coherence and hierarchy within the whole mystery of Christ.", "src.ccc.interpretation"),
      magisterial("CCC 891-892", "The Catechism distinguishes infallible definitions from the ordinary exercise of authoritative teaching and the responses they call for."),
      magisterial("Dei Verbum 10", "The council distinguishes the teaching office from the Word it serves and locates Scripture, Tradition, and Magisterium within one divine plan.", "src.vatican2.dei-verbum"),
    ],
    patristicHistoricalEvidence: historical("Early disputes already required Christians to distinguish the apostolic rule of faith from private speculation and local practice.", [
      { summary: "Irenaeus contrasts the churches' public apostolic tradition with speculative systems claimed by rival teachers.", sourceId: "src.irenaeus.against-heresies", locator: "Against Heresies III.3" },
    ]),
    importantDistinctions: [
      distinctions("Claim categories and their proper questions", [
        ["Dogma", "Divinely revealed truth definitively proposed", "Ask how it is contained in revelation and proposed by the Church"],
        ["Doctrine", "Authoritative teaching in faith or morals", "Ask its level, object, continuity, and required response"],
        ["Discipline", "Changeable ecclesial regulation or practice", "Ask who enacted it, whom it binds, and its doctrinal rationale"],
        ["Theological opinion", "Permitted non-definitive theological judgment", "Ask whether it fits established teaching and how strongly evidence supports it"],
        ["Historical claim", "Judgment about a contingent past event", "Ask about sources, method, probability, and competing interpretations"],
      ]),
    ],
    strongObjection: "Catholics use labels such as 'discipline' or 'opinion' as escape hatches whenever the Church appears to have changed or made a mistake.",
    opposingPosition: "The objection reasonably demands consistent classifications rather than after-the-fact relabelling. It also notes that disciplines can express doctrine and that historical claims sometimes affect the credibility of doctrinal narratives.",
    catholicResponse: "The categories are not excuses; they impose harder questions. A Catholic must identify the competent authority, text, object, level of teaching, historical context, and response required. A discipline cannot be used to deny a dogma, and calling something doctrine does not make every explanation of it irreformable. Where classification is contested, the honest answer is to flag it for qualified review rather than claim certainty.",
    commonMistakes: [
      "Calling every papal remark infallible.",
      "Calling every long-standing Catholic practice a dogma.",
      "Assuming a change in discipline proves a reversal of doctrine.",
      "Presenting a favored theological school as the only Catholic position.",
      "Using a doctrinal citation to avoid evaluating a separate historical claim.",
    ],
    practicalSpiritualApplication: "Choose a disputed Catholic claim and write five lines: exact wording, speaker or document, claim type, authority level, and evidence still needed. Practice saying 'I do not yet know the classification' when the record is incomplete.",
    summary: "Catholic reasoning improves when it distinguishes dogma, broader doctrine, discipline, theological opinion, and historical claim. The categories do not remove the duty to seek truth; they direct the right evidence, authority question, and degree of confidence to each claim.",
    reviewPrompts: [
      "Why is 'doctrine' broader than 'dogma'?",
      "How can a discipline change while a doctrine remains?",
      "What evidence is needed before classifying a contested statement?",
    ],
    practiceIntents: [
      ["multiple_choice", "Classify representative Catholic statements by claim type."],
      ["scenario", "Identify which authority and evidence questions are missing from an online dispute."],
    ],
    references: [
      reference("src.scripture.1-timothy-3", "1 Timothy 3:14-15", "Church, truth, and ecclesial conduct"),
      reference("src.scripture.ephesians-4", "Ephesians 4:11-16", "Teaching ministry, unity, and doctrinal maturity"),
      reference("src.scripture.acts-2", "Acts 2:42", "Perseverance in apostolic teaching"),
      reference("src.ccc.interpretation", "CCC 84-90", "Deposit of faith, Magisterium, dogmas, and hierarchy"),
      reference("src.ccc.main", "CCC 891-892", "Modes of Magisterial teaching"),
      reference("src.vatican2.dei-verbum", "Section 10", "Teaching office in service to revelation"),
      reference("src.irenaeus.against-heresies", "Book III, chapter 3", "Apostolic tradition and rival speculation"),
    ],
    relatedLessonIds: ["les.catholic-foundations.distinctions.02", "les.revelation-and-faith.distinctions.01", "les.papacy-and-magisterium.distinctions.01"],
    graphCategoryIds: ["historical", "papacy"],
    doctrinalClassifications: ["dogma", "doctrine", "discipline", "theological_opinion", "historical_claim"],
    comparativeTraditions: [],
  },
  {
    phase3LessonId: "les.catholic-foundations.distinctions.02",
    centralQuestion: "What does the Catholic 'hierarchy of truths' mean, and what does it not mean?",
    learningObjectives: [
      "Define the hierarchy of truths as an ordering by relationship to the foundation of Christian faith.",
      "Distinguish doctrinal centrality from truth, certainty, and the obligation of assent.",
      "Use doctrinal proportion in catechesis without suppressing difficult teachings.",
    ],
    shortDirectAnswer: "The hierarchy of truths means that Catholic doctrines have different relationships to the foundation of Christian faith in the Trinity and Christ's saving mystery. It does not mean that some revealed truths are false, dispensable, or open to denial.",
    fullExplanation: [
      heading("An order within one faith"),
      paragraph("Catholic doctrine is an organic whole, yet not every doctrine functions as the immediate centre of every explanation. The Trinity, Incarnation, and Paschal Mystery illuminate teachings about grace, Church, sacraments, morality, prayer, and final destiny. The hierarchy is therefore relational: it asks how a teaching connects to the foundation and how it helps disclose the saving mystery.", ["src.ccc.interpretation", "src.vatican2.unitatis-redintegratio"]),
      heading("Centrality is not a truth-value scale"),
      paragraph("A doctrine does not become less true because it is less foundational. Nor does 'pastoral' communication permit concealment or contradiction. Proportion governs sequence, emphasis, and connection. The central proclamation should remain visible, while the full faith is taught in an ordered way appropriate to the learner and question.", ["src.francis.evangelii-gaudium", "src.vatican2.unitatis-redintegratio"]),
      heading("Why apologists need proportion"),
      paragraph("Controversy naturally magnifies disputed issues. An apologist can spend hours on a Marian title, a disciplinary scandal, or a difficult historical episode without ever explaining the triune God or Christ's victory. The solution is not to evade the dispute but to locate it: state the Catholic claim accurately, its level, its link to more central mysteries, and the evidence appropriate to it.", ["src.ccc.interpretation", "src.francis.evangelii-gaudium"]),
    ],
    essentialTerminology: [
      { term: "Hierarchy of truths", definition: "The ordering of doctrines according to their differing relationships to the foundation of Christian faith.", sourceIds: ["src.vatican2.unitatis-redintegratio", "src.ccc.interpretation"] },
      { term: "Doctrinal proportion", definition: "Presenting each teaching with emphasis, sequence, and context suited to its place within the whole Gospel.", sourceIds: ["src.francis.evangelii-gaudium"] },
      { term: "Organic unity", definition: "The mutual connection of the mysteries of faith within the one saving plan of God.", sourceIds: ["src.ccc.interpretation"] },
      { term: "Foundation", definition: "Here, the triune God and the saving mystery of Christ from which other teachings receive their Christian meaning and connection.", sourceIds: ["src.vatican2.unitatis-redintegratio"] },
    ],
    scriptureEvidence: [
      scripture("1 Corinthians 15:1-5", "Paul can transmit a broad apostolic teaching while marking Christ's death and resurrection as matters of first importance.", "src.scripture.1-corinthians-15"),
      scripture("Matthew 28:18-20", "Christian initiation and mission are explicitly ordered to the Father, Son, and Holy Spirit and to the whole teaching of Christ.", "src.scripture.matthew-28"),
      scripture("Ephesians 4:1-16", "Paul joins one faith and baptism to growth into the fullness of Christ, holding unity and maturation together.", "src.scripture.ephesians-4"),
    ],
    catechismMagisterialEvidence: [
      magisterial("CCC 90", "The Catechism states that a hierarchy exists because doctrines differ in their relationship to the foundation of Christian faith.", "src.ccc.interpretation"),
      magisterial("Unitatis Redintegratio 11", "The council asks Catholic explanation, especially in ecumenical dialogue, to observe the hierarchy of truths while expressing the full faith.", "src.vatican2.unitatis-redintegratio"),
      magisterial("Evangelii Gaudium 34-39", "Francis applies hierarchy and proportion to evangelizing proclamation so that secondary emphases do not eclipse the Gospel's heart.", "src.francis.evangelii-gaudium"),
      magisterial("CCC 234", "The Catechism identifies the mystery of the Most Holy Trinity as central to Christian faith and life."),
    ],
    patristicHistoricalEvidence: historical("The Church's creedal practice shows an ordered summary of the whole faith around the triune God and Christ's saving work.", [
      { summary: "Cyril explains the Creed as a concise, ordered presentation for catechumens rather than an exhaustive replacement for Scripture.", sourceId: "src.cyril.catechetical-lectures", locator: "Catechetical Lecture 5" },
    ]),
    importantDistinctions: [
      distinctions("Questions the hierarchy does and does not answer", [
        ["Centrality", "How directly a doctrine relates to the foundation", "Guides order and emphasis"],
        ["Truth", "Whether the claim corresponds to reality and revelation", "A less central doctrine is not thereby less true"],
        ["Certainty or authority", "How the claim is taught and what assent it requires", "Must be assessed by its own doctrinal status"],
        ["Pastoral sequence", "When and how to introduce a teaching", "Can adapt to learners without falsifying content"],
      ]),
    ],
    strongObjection: "If all defined dogmas are binding, speaking of a hierarchy either changes nothing or quietly licenses Catholics to ignore unpopular doctrines.",
    opposingPosition: "The objection correctly separates binding authority from rhetorical preference. It resists using 'central' as a synonym for 'the only thing that matters.'",
    catholicResponse: "The hierarchy answers a different question from the degree of assent. It maps relationship to the foundation and therefore matters greatly for explanation, ecumenical dialogue, curriculum order, and spiritual integration. It never grants permission to deny a truth. Instead, it helps show why a teaching belongs and prevents it from appearing as an isolated burden.",
    commonMistakes: [
      "Calling secondary truths optional or merely symbolic.",
      "Confusing hierarchy with a ranking of certainty.",
      "Using a difficult secondary controversy as the first explanation of Catholicism.",
      "Invoking the Gospel centre to avoid answering a legitimate doctrinal question.",
    ],
    practicalSpiritualApplication: "Take one Catholic teaching you find difficult. Draw a three-step chain from that teaching to Christ's saving work and the Trinity. If a link is weak, note the missing concept for study rather than demoting the teaching by preference.",
    summary: "The hierarchy of truths orders one coherent faith around its triune and Christological foundation. It guides proportion and pedagogy, not selective belief. Good apologetics tells the whole truth while making its centre and connections unmistakable.",
    reviewPrompts: [
      "What relationship does the hierarchy of truths measure?",
      "Why does hierarchy not imply that some revealed doctrines may be denied?",
      "How should doctrinal proportion change an apologetic answer?",
    ],
    practiceIntents: [
      ["true_false", "Distinguish centrality from truth and required assent."],
      ["scenario", "Reorder an apologetic explanation so its Christological centre remains visible."],
    ],
    references: [
      reference("src.scripture.1-corinthians-15", "1 Corinthians 15:1-5", "Apostolic use of ordered importance"),
      reference("src.scripture.matthew-28", "Matthew 28:18-20", "Trinitarian foundation and comprehensive teaching"),
      reference("src.scripture.ephesians-4", "Ephesians 4:1-16", "One faith ordered toward mature fullness in Christ"),
      reference("src.ccc.interpretation", "CCC 90", "Definition of hierarchy of truths"),
      reference("src.ccc.main", "CCC 234", "Centrality of the Trinity"),
      reference("src.vatican2.unitatis-redintegratio", "Section 11", "Full presentation and hierarchy in ecumenical dialogue"),
      reference("src.francis.evangelii-gaudium", "Sections 34-39", "Pastoral and missionary proportion"),
      reference("src.cyril.catechetical-lectures", "Catechetical Lecture 5", "Creedal synthesis in early catechesis"),
    ],
    relatedLessonIds: ["les.catholic-foundations.distinctions.01", "les.catholic-foundations.synthesis.01", "les.trinity.foundations.01"],
    graphCategoryIds: ["trinity", "christology"],
    doctrinalClassifications: ["dogma", "doctrine"],
    comparativeTraditions: [],
  },
  {
    phase3LessonId: "les.catholic-foundations.evidence.01",
    centralQuestion: "How do Sacred Scripture, Sacred Tradition, and the Magisterium relate in Catholic faith?",
    learningObjectives: [
      "Describe Scripture, Tradition, and Magisterium without treating them as three rival sources.",
      "Distinguish apostolic Tradition from local customs and the Magisterium from new revelation.",
      "Represent a confessional Reformed objection to Catholic authority fairly before giving a Catholic response.",
    ],
    shortDirectAnswer: "Scripture and Tradition transmit the one apostolic deposit of God's revelation, while the Magisterium authentically interprets that deposit in service to the Word of God. None operates properly in isolation, and the Magisterium does not create new public revelation.",
    fullExplanation: [
      heading("One deposit transmitted in related modes"),
      paragraph("The Catholic account begins with God's self-revelation completed in Christ and entrusted to the apostles. Their Gospel is transmitted in inspired writings and in the Church's living apostolic Tradition. Scripture is the Word of God set down under the inspiration of the Holy Spirit; Tradition hands on the Word entrusted by Christ and the Spirit to the apostles. They flow from the same divine source and converge toward the same end.", ["src.vatican2.dei-verbum", "src.ccc.interpretation"]),
      heading("A teaching office that serves"),
      paragraph("The Magisterium is the teaching office exercised by the bishops in communion with the Bishop of Rome. It is not above the Word of God and does not add a second stream of fresh public revelation. Its task is to listen, guard, expound, and authentically judge what belongs to the apostolic deposit. Scripture, Tradition, and Magisterium therefore have different roles within one economy of transmission.", ["src.vatican2.dei-verbum", "src.ccc.interpretation"]),
      heading("Tradition is not every tradition"),
      paragraph("Apostolic Tradition must be distinguished from theological, liturgical, devotional, or disciplinary traditions that arose in particular times and places. Such traditions may be valuable and may express the faith, but they can be reformed under the Church's authority. The distinction prevents both contempt for living transmission and the inflation of every custom into revelation.", ["src.ccc.interpretation"]),
    ],
    essentialTerminology: [
      { term: "Deposit of faith", definition: "The saving revelation entrusted by Christ and the Holy Spirit to the apostles and handed on in the Church.", sourceIds: ["src.ccc.interpretation"] },
      { term: "Sacred Scripture", definition: "The inspired written Word of God received in the Church's canon.", sourceIds: ["src.vatican2.dei-verbum"] },
      { term: "Sacred Tradition", definition: "The living transmission of the apostolic Gospel in the Church under the Holy Spirit, distinct from merely local or changeable customs.", sourceIds: ["src.vatican2.dei-verbum", "src.ccc.interpretation"] },
      { term: "Magisterium", definition: "The Church's living teaching office, exercised by the bishops in communion with the successor of Peter, in service to the Word of God.", sourceIds: ["src.vatican2.dei-verbum", "src.ccc.interpretation"] },
    ],
    scriptureEvidence: [
      scripture("1 Corinthians 15:1-5", "Paul describes a Gospel that he received, handed on, and also attests through the scriptural witness to Christ's saving death and resurrection.", "src.scripture.1-corinthians-15"),
      scripture("2 Timothy 2:1-2", "Timothy is to entrust Paul's received teaching to reliable people capable of teaching others, displaying an ordered chain of transmission.", "src.scripture.2-timothy-2"),
      scripture("Acts 2:42", "The first baptized community perseveres in the apostles' teaching within the worshiping life of the Church.", "src.scripture.acts-2"),
      scripture("1 Timothy 3:14-15", "Paul links ordered ecclesial life with the Church's responsibility toward the truth.", "src.scripture.1-timothy-3"),
    ],
    catechismMagisterialEvidence: [
      magisterial("Dei Verbum 7-10", "The council explains apostolic transmission, the relationship of Scripture and Tradition, and the Magisterium's servant role.", "src.vatican2.dei-verbum"),
      magisterial("CCC 74-83", "The Catechism summarizes the handing on of revelation and distinguishes apostolic Tradition from later ecclesial traditions.", "src.ccc.interpretation"),
      magisterial("CCC 84-87", "The deposit is entrusted to the Church, and authentic interpretation is assigned to the living teaching office without placing it above God's Word.", "src.ccc.interpretation"),
      magisterial("CCC 95", "The Catechism presents Scripture, Tradition, and Magisterium as so connected that each works properly with the others.", "src.ccc.interpretation"),
    ],
    patristicHistoricalEvidence: historical("The second-century appeal to public apostolic succession and teaching is evidence for a living, ecclesial account of transmission very near the apostolic age.", [
      { summary: "Irenaeus answers secret or revisionist teachings by pointing to the publicly traceable apostolic tradition preserved in the churches.", sourceId: "src.irenaeus.against-heresies", locator: "Against Heresies III.3" },
    ]),
    importantDistinctions: [
      distinctions("Three roles within one transmission", [
        ["Scripture", "Inspired written witness within the apostolic deposit", "Normative Word of God, read in the living Church"],
        ["Apostolic Tradition", "Living transmission of the Gospel entrusted to the apostles", "Includes more than changeable customs"],
        ["Magisterium", "Authentic ecclesial interpretation of the deposit", "Serves rather than supersedes the Word"],
        ["Ecclesial traditions", "Later theological, liturgical, devotional, or disciplinary forms", "May express the faith yet can be distinguished and reformed"],
      ]),
    ],
    strongObjection: "Scripture is sufficient as the only infallible rule; adding an unwritten Tradition and an infallible Magisterium subjects God's Word to human authorities.",
    opposingPosition: "Confessional Reformed Christianity classically teaches that the whole counsel necessary for salvation, faith, and life is expressly set down in Scripture or can be deduced from it, and that the supreme judge of religious controversies is the Holy Spirit speaking in Scripture. Reformed churches still use creeds, teachers, and inherited interpretation, but deny that these form a second infallible rule alongside Scripture. Other Protestant traditions formulate authority differently.",
    catholicResponse: "Catholic teaching agrees that the Magisterium is under and serves God's Word, not over it. The disagreement concerns how Christ willed the apostolic Gospel to remain identifiable and authoritatively interpreted. The New Testament itself is received within apostolic teaching, worship, and ordered transmission. Catholicism therefore sees Scripture and apostolic Tradition as inseparable modes of one deposit and the Magisterium as its servant interpreter, not as competing revelations. Later lessons must examine canon, succession, and particular definitions rather than treating this introductory synthesis as a complete proof.",
    commonMistakes: [
      "Calling Scripture, Tradition, and Magisterium three separate revelations.",
      "Using 'Tradition' to defend every Catholic custom.",
      "Saying the Magisterium can teach whatever it chooses.",
      "Representing all Protestants as holding one identical version of sola Scriptura.",
      "Citing a Church Father as if one passage alone settles the whole authority question.",
    ],
    practicalSpiritualApplication: "When studying a doctrine, record three columns: principal biblical texts, the Church's received interpretation and practice, and the relevant Magisterial judgment. Use the columns to seek coherence, not to make one source silence the others.",
    summary: "Catholicism receives one apostolic deposit through inspired Scripture and living apostolic Tradition, authentically interpreted by a Magisterium that serves God's Word. This framework must be distinguished from both private custom and the claim that ecclesial authority creates new revelation.",
    reviewPrompts: [
      "Why does Catholic teaching reject the image of three rival sources?",
      "How does apostolic Tradition differ from later ecclesial traditions?",
      "State the Reformed concern about authority without caricature, then identify the precise Catholic disagreement.",
    ],
    practiceIntents: [
      ["multiple_choice", "Match Scripture, Tradition, and Magisterium to their distinct roles."],
      ["short_response", "Fairly state the Reformed objection and the Catholic reply."],
    ],
    references: [
      reference("src.scripture.1-corinthians-15", "1 Corinthians 15:1-5", "Received and transmitted apostolic Gospel"),
      reference("src.scripture.2-timothy-2", "2 Timothy 2:1-2", "Ordered teaching transmission"),
      reference("src.scripture.acts-2", "Acts 2:42", "Apostolic teaching in ecclesial life"),
      reference("src.scripture.1-timothy-3", "1 Timothy 3:14-15", "Ecclesial order and responsibility toward truth"),
      reference("src.vatican2.dei-verbum", "Sections 7-10", "Catholic account of transmission and authority"),
      reference("src.ccc.interpretation", "CCC 74-95", "Scripture, Tradition, deposit, Magisterium, and traditions"),
      reference("src.irenaeus.against-heresies", "Book III, chapter 3", "Public apostolic tradition"),
      reference("src.reformed.westminster-confession", "Chapter 1, sections 6 and 10", "Confessional Reformed account represented in the objection"),
    ],
    relatedLessonIds: ["les.catholic-foundations.evidence.02", "les.revelation-and-faith.foundations.01", "les.scripture-and-canon.foundations.01"],
    graphCategoryIds: ["canon", "historical", "papacy", "protestant"],
    doctrinalClassifications: ["dogma", "doctrine", "historical_claim"],
    comparativeTraditions: ["Confessional Reformed Protestantism (Westminster tradition; not all Protestants)"],
  },
  {
    phase3LessonId: "les.catholic-foundations.evidence.02",
    centralQuestion: "How do belief, worship, moral life, and prayer provide mutually supporting evidence for the coherence of Catholic faith?",
    learningObjectives: [
      "Explain how Creed, sacraments, moral life, and prayer interpret and test one another.",
      "Distinguish a cumulative Catholic case from a single proof-text or isolated historical argument.",
      "Construct a simple four-dimensional evidence map for one Catholic claim.",
    ],
    shortDirectAnswer: "Catholic faith is presented as a lived whole: what the Church believes identifies the God she worships; sacramental worship enacts the mystery confessed; moral life shows the human shape of grace; and prayer expresses communion with God. Their convergence does not remove the need to test particular claims, but it gives a richer cumulative case than any isolated citation.",
    fullExplanation: [
      heading("The whole life of faith bears witness"),
      paragraph("A creed can be recited without being understood, a ritual can be performed without conversion, and a moral ideal can be admired without grace. Catholic formation therefore does not treat one dimension as self-sufficient. Apostolic teaching, sacramental communion, shared life, and prayer appear together in Acts, and the Catechism deliberately preserves that integration.", ["src.scripture.acts-2", "src.ccc.main"]),
      heading("A cumulative case uses different kinds of evidence"),
      paragraph("Scriptural exegesis asks what a text means in its literary and canonical context. Historical study asks what communities believed and practiced and how sources should be weighed. Doctrinal reasoning asks how claims cohere with the whole deposit. Liturgy and sanctity are not shortcuts around those tasks, but they are relevant evidence about how the faith has been received and embodied.", ["src.vatican2.dei-verbum", "src.vatican2.sacrosanctum-concilium", "src.didache"]),
      heading("Convergence is not immunity from criticism"),
      paragraph("A coherent Catholic pattern does not make every Catholic person's conduct coherent, nor does devotional popularity prove divine revelation. Each claim still needs evidence and classification. The cumulative approach is disciplined when it states what each source can establish, acknowledges tensions, and avoids making a practice carry more weight than it can bear.", ["src.ccc.main", "src.scripture.james-1"]),
    ],
    essentialTerminology: [
      { term: "Cumulative case", definition: "An argument in which several relevant and partly independent lines of evidence converge toward a conclusion.", sourceIds: ["src.vatican2.dei-verbum"] },
      { term: "Lex orandi", definition: "A shorthand for the Church's rule or pattern of prayer, considered in relation to the faith she professes and the life she lives.", sourceIds: ["src.vatican2.sacrosanctum-concilium"] },
      { term: "Coherence", definition: "The fitting consistency and mutual illumination of claims within the whole faith; coherence supports but does not by itself prove every claim.", sourceIds: ["src.ccc.main"] },
      { term: "Embodied witness", definition: "The expression of professed faith through worship, virtue, communal practice, and concrete action.", sourceIds: ["src.scripture.james-1", "src.scripture.romans-12"] },
    ],
    scriptureEvidence: [
      scripture("Acts 2:37-47", "The baptized community holds together apostolic teaching, communion, breaking of bread, prayer, care for needs, and public witness.", "src.scripture.acts-2"),
      scripture("Romans 12:1-2", "Paul describes embodied self-offering and renewed discernment as fitting worship.", "src.scripture.romans-12"),
      scripture("James 1:22-27", "Hearing God's word must issue in action, disciplined speech, mercy, and holiness rather than self-deception.", "src.scripture.james-1"),
      scripture("Colossians 3:12-17", "Doctrine, virtue, worship, gratitude, and ordinary action are integrated under the lordship of Christ.", "src.scripture.colossians-3"),
    ],
    catechismMagisterialEvidence: [
      magisterial("CCC 13-17", "The four-part organization itself witnesses to the interdependence of profession, celebration, moral life, and prayer."),
      magisterial("CCC 1066-1075", "The sacramental economy is rooted in the Paschal Mystery confessed by the Church."),
      magisterial("CCC 1691-1698", "Christian morality is presented as grace-enabled life in Christ rather than an independent ethics system."),
      magisterial("Sacrosanctum Concilium 10", "The council relates liturgical worship to the Church's entire activity and mission.", "src.vatican2.sacrosanctum-concilium"),
      magisterial("Dei Verbum 8", "The council describes apostolic Tradition as developing in the Church's contemplation, study, lived understanding, and preaching.", "src.vatican2.dei-verbum"),
    ],
    patristicHistoricalEvidence: historical("Very early Christian sources combine instruction, worship, moral demands, and community practice, giving historical evidence against treating these as late, unrelated additions.", [
      { summary: "The Didache moves between the way of life, baptism, fasting, prayer, Eucharistic practice, and community discipline.", sourceId: "src.didache", locator: "Didache 1-4; 7-10; 14" },
    ]),
    importantDistinctions: [
      distinctions("What each dimension contributes", [
        ["Creed", "Identifies the God, events, and promises confessed", "Supplies doctrinal content and guards worship from ambiguity"],
        ["Sacramental worship", "Enacts and receives the saving mystery ecclesially", "Displays how doctrine is prayed and celebrated"],
        ["Moral life", "Shows the human action and character grace is ordered to produce", "Tests empty profession without making holiness a private achievement"],
        ["Prayer", "Expresses dependence, praise, repentance, petition, and communion", "Reveals faith's personal and relational end"],
      ]),
    ],
    strongObjection: "Appealing to Catholic worship and life is circular: Catholic practices cannot serve as evidence for doctrines that supposedly justify those same practices.",
    opposingPosition: "The objection is correct when an argument simply assumes that every Catholic practice is apostolic or that coherence equals truth. It presses Catholics to offer external textual and historical evidence and to distinguish ancient reception from later custom.",
    catholicResponse: "A cumulative case need not treat practice as self-authenticating. Scripture, historical testimony, doctrinal continuity, worship, and moral fruit ask partly different questions and can correct one another. Liturgical practice may show early reception; it cannot alone prove every later formulation. Moral failure can discredit a witness without logically falsifying the Creed. The Catholic case is strongest when the limits of each line are stated and the lines genuinely converge.",
    commonMistakes: [
      "Treating coherence as a substitute for historical or exegetical evidence.",
      "Assuming every old practice is apostolic.",
      "Arguing that a saint's holiness proves every contested Catholic claim.",
      "Using Christian moral failure as if it were irrelevant to witness.",
      "Collecting citations without explaining how they support the conclusion.",
    ],
    practicalSpiritualApplication: "Choose one belief such as the Resurrection. Make four notes: how it is professed, celebrated, lived, and prayed. Then add the independent scriptural and historical questions that still need to be answered.",
    summary: "Catholic evidence is cumulative and embodied. Creed, sacraments, moral life, and prayer mutually illuminate the one mystery of Christ, while Scripture, history, and careful reasoning test particular claims. Convergence is valuable only when each source's proper weight and limits are respected.",
    reviewPrompts: [
      "What makes an argument cumulative rather than merely repetitive?",
      "How can worship be relevant evidence without becoming self-authenticating?",
      "What limitation belongs to each of the four dimensions?",
    ],
    practiceIntents: [
      ["scenario", "Build a four-dimensional evidence map without overstating any source."],
      ["true_false", "Distinguish coherence, historical evidence, and proof."],
    ],
    references: [
      reference("src.scripture.acts-2", "Acts 2:37-47", "Integrated apostolic community"),
      reference("src.scripture.romans-12", "Romans 12:1-2", "Embodied worship and transformation"),
      reference("src.scripture.james-1", "James 1:22-27", "Hearing joined to action"),
      reference("src.scripture.colossians-3", "Colossians 3:12-17", "Virtue, teaching, worship, and action in Christ"),
      reference("src.ccc.main", "CCC 13-17; 1066-1075; 1691-1698", "Four-part unity and life in Christ"),
      reference("src.vatican2.dei-verbum", "Section 8", "Living reception of apostolic Tradition"),
      reference("src.vatican2.sacrosanctum-concilium", "Section 10", "Liturgy within the Church's whole life"),
      reference("src.didache", "Chapters 1-4; 7-10; 14", "Early integrated Christian practice"),
    ],
    relatedLessonIds: ["les.catholic-foundations.foundations.02", "les.catholic-foundations.evidence.01", "les.catholic-foundations.objections.02"],
    graphCategoryIds: ["historical", "eucharist"],
    doctrinalClassifications: ["doctrine", "historical_claim", "philosophical_claim"],
    comparativeTraditions: [],
  },
  {
    phase3LessonId: "les.catholic-foundations.objections.01",
    centralQuestion: "Why should Catholics learn apologetics if faith is a gift of grace?",
    learningObjectives: [
      "Describe apologetics as a ministry of truthful, gentle, and accountable explanation.",
      "Distinguish reasons that remove obstacles from a demonstration that compels supernatural faith.",
      "Identify situations in which listening, witness, referral, or silence is better than immediate debate.",
    ],
    shortDirectAnswer: "Catholics learn apologetics to understand the faith, answer sincere questions, correct misrepresentation, and serve the Church's mission with reasons offered in gentleness. Arguments can clarify credibility and remove obstacles, but only God's grace brings a person into living faith.",
    fullExplanation: [
      heading("A service to persons and truth"),
      paragraph("Christian readiness to give an account begins by honoring Christ and includes gentleness, reverence, and a good conscience. The goal is not domination. Apologetics serves a person who deserves to hear the Catholic claim accurately, including what is known, what is probable, and what remains disputed.", ["src.scripture.1-peter-3", "src.scripture.2-timothy-2"]),
      heading("Reasons prepare; grace converts"),
      paragraph("Historical, philosophical, and textual arguments can show that belief is not irrational, expose a false dilemma, or make a disputed Catholic claim intelligible. They cannot manufacture love of God, repentance, or supernatural assent. Mission therefore joins proclamation and teaching to prayer, sacramental life, holiness, patience, and reliance on the Holy Spirit.", ["src.scripture.matthew-28", "src.ccc.main", "src.jp2.catechesi-tradendae"]),
      heading("Formation precedes responsible defense"),
      paragraph("An apologist has duties to both the questioner and the truth. Those duties include understanding the issue, citing sources in context, naming the relevant tradition, and recognizing limits. Sometimes the faithful response is to ask a clarifying question, research before replying, involve a pastor or specialist, or refuse a demeaning contest.", ["src.scripture.james-1", "src.scripture.2-timothy-2"]),
    ],
    essentialTerminology: [
      { term: "Apologetics", definition: "The reasoned explanation and defense of a belief or tradition; in Catholic ministry it is ordered to truth, charity, and evangelization.", sourceIds: ["src.scripture.1-peter-3"] },
      { term: "Credibility", definition: "The quality by which a claim is shown worthy of rational consideration or belief, without reducing supernatural faith to a forced deduction.", sourceIds: ["src.ccc.main"] },
      { term: "Evangelization", definition: "The Church's broad mission of announcing and embodying the Gospel so that people may encounter and follow Christ.", sourceIds: ["src.jp2.catechesi-tradendae"] },
      { term: "Polemic", definition: "Argument directed against a position; it can clarify real disagreement but becomes corrupt when victory replaces truth and charity.", sourceIds: ["src.scripture.2-timothy-2"] },
    ],
    scriptureEvidence: [
      scripture("1 Peter 3:13-16", "Believers are to be prepared to explain their hope while maintaining gentleness, reverence, and integrity.", "src.scripture.1-peter-3"),
      scripture("2 Timothy 2:14-26", "The Lord's servant avoids useless quarrels, teaches competently, and corrects opponents with patience and kindness.", "src.scripture.2-timothy-2"),
      scripture("Matthew 28:18-20", "The risen Christ commissions disciple-making that includes Baptism and sustained teaching.", "src.scripture.matthew-28"),
      scripture("James 1:19-22", "Quick listening, restrained speech and anger, and obedient action guard against self-deceived religious talk.", "src.scripture.james-1"),
    ],
    catechismMagisterialEvidence: [
      magisterial("CCC 153-165", "The Catechism presents faith as a grace-enabled human act that is free, reasonable, ecclesial, and persevering."),
      magisterial("CCC 849-856", "The Church's missionary mandate arises from the Trinity and must respect truth, freedom, and the mysterious work of grace."),
      magisterial("Catechesi Tradendae 18-20", "John Paul II locates catechesis within evangelization and the maturation of initial faith.", "src.jp2.catechesi-tradendae"),
      magisterial("Unitatis Redintegratio 11", "The council requires Catholic explanation to join depth, precision, and charity, especially across Christian divisions.", "src.vatican2.unitatis-redintegratio"),
    ],
    patristicHistoricalEvidence: historical("Christian apologetics appeared early as believers answered public accusations and explained their worship and moral life to outsiders.", [
      { summary: "Justin addresses imperial readers, asks for a just examination rather than punishment by label, and explains Christian claims and practices in an apologetic form.", sourceId: "src.justin.first-apology", locator: "First Apology 1-8" },
    ]),
    importantDistinctions: [
      distinctions("Purposes and limits of apologetics", [
        ["Explanation", "Make the Catholic claim intelligible and accurately bounded", "Often needed before disagreement can be assessed"],
        ["Defense", "Answer an objection or show that a claim is credible", "Can remove obstacles but cannot force faith"],
        ["Evangelization", "Announce Christ and invite conversion within the Church's whole mission", "Broader than argument and dependent on grace"],
        ["Debate", "A structured contest between positions", "Sometimes useful, never the default measure of faithful witness"],
      ]),
    ],
    strongObjection: "Apologetics turns faith into intellectual combat and assumes people can be argued into a relationship with God.",
    opposingPosition: "This objection recognizes real abuses: performative debate, manipulation, selective evidence, and indifference to a questioner's wounds. It also correctly insists that conversion cannot be reduced to winning an inference.",
    catholicResponse: "Those abuses contradict the biblical manner of Christian explanation. Apologetics is legitimate when it remains a servant: it clarifies what the Church teaches, offers reasons, corrects falsehood, listens, and knows its limits. Grace does not eliminate human reasoning; it heals and elevates persons who still ask historical, moral, and intellectual questions. Sometimes the most apologetically faithful act is patient presence rather than another argument.",
    commonMistakes: [
      "Answering the question you rehearsed instead of the question actually asked.",
      "Treating uncertainty as weakness and inventing a confident answer.",
      "Assuming an opponent's motives from a label.",
      "Measuring success by public victory or immediate agreement.",
      "Using apologetics as a substitute for prayer, holiness, or pastoral care.",
    ],
    practicalSpiritualApplication: "Before answering one disputed question, pray for the questioner's good, restate the question in words they accept, and decide whether your next faithful action is an answer, a question, a source, a referral, or silence.",
    summary: "Catholic apologetics is reasoned service within evangelization. It can clarify, defend, and remove obstacles, but it cannot compel faith or replace grace, witness, worship, and love. Its biblical manner is truthful, prepared, patient, gentle, and accountable.",
    reviewPrompts: [
      "What can an apologetic argument accomplish, and what can it not accomplish?",
      "Which biblical qualities govern the manner of an answer?",
      "Name two situations in which immediate debate would be imprudent.",
    ],
    practiceIntents: [
      ["scenario", "Choose the most truthful and charitable response to a difficult question."],
      ["short_response", "Explain the relation between apologetic reasons and grace."],
    ],
    references: [
      reference("src.scripture.1-peter-3", "1 Peter 3:13-16", "Readiness, hope, gentleness, and conscience"),
      reference("src.scripture.2-timothy-2", "2 Timothy 2:14-26", "Competent and gentle correction"),
      reference("src.scripture.matthew-28", "Matthew 28:18-20", "Mission, Baptism, and teaching"),
      reference("src.scripture.james-1", "James 1:19-22", "Listening, disciplined speech, and action"),
      reference("src.ccc.main", "CCC 153-165; 849-856", "Faith, reason, grace, freedom, and mission"),
      reference("src.jp2.catechesi-tradendae", "Sections 18-20", "Catechesis within evangelization"),
      reference("src.vatican2.unitatis-redintegratio", "Section 11", "Qualified and charitable explanation"),
      reference("src.justin.first-apology", "Chapters 1-8", "Early Christian public apologetic"),
    ],
    relatedLessonIds: ["les.catholic-foundations.objections.02", "les.catholic-foundations.synthesis.02", "les.debate-reasoning-source-evaluation.foundations.01"],
    graphCategoryIds: ["historical", "protestant", "secular"],
    doctrinalClassifications: ["doctrine", "historical_claim", "philosophical_claim"],
    comparativeTraditions: [],
  },
  {
    phase3LessonId: "les.catholic-foundations.objections.02",
    centralQuestion: "How can a Catholic avoid proof-texting, triumphalism, and false certainty while still giving a clear defense?",
    learningObjectives: [
      "Identify proof-texting, triumphalism, and false certainty in sample arguments.",
      "Apply context, source hierarchy, claim classification, and confidence labels to an apologetic answer.",
      "Explain why intellectual humility strengthens rather than weakens Catholic witness.",
    ],
    shortDirectAnswer: "A responsible Catholic reads texts in context and within the whole canon, represents others in terms they recognize, distinguishes doctrine from opinion and history, and matches confidence to evidence. Clarity concerns what the Church teaches; humility concerns the limits of the speaker and argument.",
    fullExplanation: [
      heading("A citation is not yet an interpretation"),
      paragraph("Proof-texting extracts a line from its literary, historical, canonical, or doctrinal context and makes it bear more than it can establish. A sound answer first asks who is speaking, to whom, about what, in which genre, and how the passage fits the whole of Scripture. Catholic interpretation also attends to the unity of Scripture, living Tradition, and the analogy of faith.", ["src.vatican2.dei-verbum", "src.ccc.main"]),
      heading("Truth is not served by triumphalism"),
      paragraph("Triumphalism narrates Catholic history as though grace erased sin, prudential failure, coercion, or legitimate complexity. It may also treat every opponent as dishonest. The Church's holiness comes from Christ and the Spirit, while her members remain in need of purification. Honest confession of failure does not require denying the truth of the Gospel or the real holiness present in the Church.", ["src.ccc.main", "src.vatican2.unitatis-redintegratio"]),
      heading("Confidence must track the claim"),
      paragraph("A defined dogma, an authoritative but non-definitive doctrine, a disciplinary judgment, a theological explanation, and a reconstruction of motives do not carry identical certainty. The apologist should use calibrated language: 'the Church teaches,' 'a common theological account is,' 'the evidence suggests,' or 'I do not know.' This is accuracy, not evasion.", ["src.ccc.interpretation", "src.scripture.james-1"]),
    ],
    essentialTerminology: [
      { term: "Proof-texting", definition: "Using a short citation apart from relevant context or as though the citation alone establishes a larger disputed conclusion.", sourceIds: ["src.vatican2.dei-verbum"] },
      { term: "Triumphalism", definition: "A self-congratulatory account that minimizes sin, complexity, dependence on grace, or truth present in others.", sourceIds: ["src.vatican2.unitatis-redintegratio"] },
      { term: "False certainty", definition: "Claiming a degree of confidence, authority, or precision not warranted by the sources or the type of claim.", sourceIds: ["src.ccc.interpretation"] },
      { term: "Analogy of faith", definition: "The coherence of the truths of faith with one another and within the whole plan of revelation.", sourceIds: ["src.ccc.main"] },
    ],
    scriptureEvidence: [
      scripture("2 Timothy 2:14-26", "Paul warns against word battles and foolish disputes while requiring patient, gentle, capable instruction.", "src.scripture.2-timothy-2"),
      scripture("James 1:19-22", "Believers are to listen readily, restrain speech and anger, and become doers rather than self-deceived hearers.", "src.scripture.james-1"),
      scripture("1 Peter 3:15-16", "A defense of hope must be joined to reverence, gentleness, and integrity.", "src.scripture.1-peter-3"),
      scripture("Luke 24:25-49", "Jesus interprets a broad scriptural pattern concerning the Messiah rather than isolating an unexplained fragment.", "src.scripture.luke-24"),
    ],
    catechismMagisterialEvidence: [
      magisterial("CCC 109-119", "The Catechism summarizes attention to authorial intention, literary forms, the Spirit's guidance, canonical unity, Tradition, and the analogy of faith."),
      magisterial("Dei Verbum 12", "The council requires attention to literary, historical, and canonical dimensions while reading Scripture in the Spirit in whom it was written.", "src.vatican2.dei-verbum"),
      magisterial("CCC 84-90; 891-892", "Different teaching acts and claim types call for accurate classification and response.", "src.ccc.interpretation"),
      magisterial("Unitatis Redintegratio 4 and 11", "Ecumenical engagement requires conversion, fairness, charity, and accurate presentation of the full Catholic faith.", "src.vatican2.unitatis-redintegratio"),
    ],
    patristicHistoricalEvidence: historical("Patristic controversy shows both the need to read Scripture as a coherent whole and the danger of rearranging fragments into a foreign picture.", [
      { summary: "Irenaeus argues that biblical phrases can be rearranged into a misleading system when the Church's received rule of faith is discarded.", sourceId: "src.irenaeus.against-heresies", locator: "Against Heresies I.8" },
      { summary: "Augustine's interpretive work repeatedly connects responsible reading with the rule of faith and the goal of love of God and neighbor.", sourceId: "src.augustine.christian-doctrine", locator: "On Christian Doctrine I and III" },
    ]),
    importantDistinctions: [
      distinctions("Three failures and their remedies", [
        ["Proof-texting", "Overloads an isolated citation", "Read literary and canonical context; state exactly what the text supports"],
        ["Triumphalism", "Confuses fidelity with self-exaltation", "Tell the truth about grace, sin, history, and goods found in others"],
        ["False certainty", "Claims more confidence than evidence permits", "Classify the claim and use calibrated language"],
        ["Clear conviction", "States a warranted conclusion plainly", "Compatible with humility about oneself and fair treatment of objections"],
      ]),
    ],
    strongObjection: "Qualifications and humility merely weaken the case; if Catholicism is true, its defenders should speak with unhesitating certainty.",
    opposingPosition: "The objection values clarity and fears that endless caveats will make teaching impossible. It also recognizes that some Catholic claims, especially dogmas, are presented as definitive rather than tentative hypotheses.",
    catholicResponse: "Clarity and calibration are allies. One can state a dogma clearly while admitting that a favorite proof-text is not conclusive, a historical date is uncertain, or an opponent's motive is unknown. Overclaiming gives critics an easy reason to distrust even the stronger case. Humility concerns fidelity to truth: no less confidence than warranted and no more.",
    commonMistakes: [
      "Quoting a verse without reading the paragraph, book, or major alternative interpretation.",
      "Using a secondary apologetics summary when a primary source is available.",
      "Describing another tradition only by Catholic critics of it.",
      "Treating admission of Catholic sin as surrender of Catholic doctrine.",
      "Turning a probable historical reconstruction into a claim that the Church teaches.",
    ],
    practicalSpiritualApplication: "Revise one answer you have given online. Add the surrounding context, one fair sentence for the strongest alternative reading, a claim classification, and a confidence label. Remove any assertion about another person's motives.",
    summary: "Responsible apologetics interprets rather than merely cites, tells the truth about the Church's members and history, and calibrates confidence to evidence and authority. These disciplines make conviction more credible because they place the defense under the truth it serves.",
    reviewPrompts: [
      "What questions should be asked before using a biblical citation as evidence?",
      "How does clear conviction differ from false certainty?",
      "Why can acknowledging Catholic failure strengthen an apologetic answer?",
    ],
    practiceIntents: [
      ["scenario", "Diagnose proof-texting, triumphalism, or false certainty in a sample answer."],
      ["short_response", "Rewrite an overconfident claim with accurate classification and confidence."],
    ],
    references: [
      reference("src.scripture.2-timothy-2", "2 Timothy 2:14-26", "Manner of dispute and correction"),
      reference("src.scripture.james-1", "James 1:19-22", "Listening, speech, anger, and action"),
      reference("src.scripture.1-peter-3", "1 Peter 3:15-16", "Gentle, conscientious defense"),
      reference("src.scripture.luke-24", "Luke 24:25-49", "Christological reading across the scriptural whole"),
      reference("src.vatican2.dei-verbum", "Section 12", "Principles of Catholic biblical interpretation"),
      reference("src.ccc.main", "CCC 109-119", "Scriptural senses and interpretive criteria"),
      reference("src.ccc.interpretation", "CCC 84-90; 891-892", "Claim and authority classification"),
      reference("src.vatican2.unitatis-redintegratio", "Sections 4 and 11", "Conversion, charity, and accurate ecumenical explanation"),
      reference("src.irenaeus.against-heresies", "Book I, chapter 8", "Misleading rearrangement of scriptural fragments"),
      reference("src.augustine.christian-doctrine", "Books I and III", "Interpretation ordered by faith and charity"),
    ],
    relatedLessonIds: ["les.catholic-foundations.objections.01", "les.catholic-foundations.synthesis.02", "les.debate-reasoning-source-evaluation.distinctions.01"],
    graphCategoryIds: ["historical", "canon", "protestant"],
    doctrinalClassifications: ["doctrine", "historical_claim", "philosophical_claim"],
    comparativeTraditions: [],
  },
  {
    phase3LessonId: "les.catholic-foundations.synthesis.01",
    centralQuestion: "How can a Catholic give a faithful two-minute account of the faith without turning it into a list?",
    learningObjectives: [
      "Give a concise account ordered by creation, the Paschal Mystery, the Spirit and Church, discipleship, and final hope.",
      "Adapt the account to a listener while preserving its Trinitarian and Christological centre.",
      "Distinguish a doorway summary from a complete proof or lesson.",
    ],
    shortDirectAnswer: "Begin with the God who creates and calls humanity, name sin and the need for salvation, proclaim the Father's gift of the incarnate Son and Christ's death and Resurrection, explain the Spirit's work in the Church and sacraments, and end with grace-enabled discipleship and resurrection hope. Then invite the listener's real question.",
    fullExplanation: [
      heading("A faithful doorway"),
      paragraph("A two-minute account cannot prove every claim or mention every devotion. Its purpose is orientation: to name the agent, action, gift, and goal of Christian faith so that later doctrines have a home. It should be recognizably Trinitarian, centred on Christ's Paschal Mystery, ecclesial rather than isolated, and directed toward communion with God.", ["src.scripture.1-corinthians-15", "src.scripture.matthew-28", "src.ccc.main"]),
      heading("A five-movement account"),
      paragraph("First, the one God freely creates human persons for communion. Second, sin wounds that vocation and cannot be healed by self-salvation. Third, the Father sends the eternal Son, who becomes man, announces the kingdom, dies, rises, and reigns. Fourth, the Holy Spirit joins believers to Christ in his Church through faith, Baptism, sacramental life, teaching, and charity. Fifth, grace forms disciples who pray, love, seek holiness and justice, and hope for resurrection and the life of the world to come.", ["src.ccc.main", "src.scripture.acts-2", "src.scripture.matthew-28"]),
      heading("Conversation, not recitation"),
      paragraph("The same centre can be expressed differently to a catechumen, a lapsed Catholic, a Protestant Christian, or a person unsure whether God exists. Adaptation means beginning near the listener's question and defining unfamiliar terms. It does not mean hiding Catholic teaching. End by asking what seems clear, implausible, attractive, or troubling; that answer determines the next lesson.", ["src.jp2.catechesi-tradendae", "src.francis.evangelii-gaudium"]),
    ],
    essentialTerminology: [
      { term: "Salvation history", definition: "The ordered history of God's creative, covenantal, redemptive, and consummating work, centred on Christ.", sourceIds: ["src.ccc.main"] },
      { term: "Incarnation", definition: "The mystery by which the eternal Son of God truly became man without ceasing to be God.", sourceIds: ["src.ccc.main"] },
      { term: "Grace", definition: "God's free and undeserved gift that heals, sanctifies, and enables participation in divine life.", sourceIds: ["src.ccc.main"] },
      { term: "Resurrection hope", definition: "Christian hope in Christ's victory, the resurrection of the body, judgment, and everlasting communion with God.", sourceIds: ["src.scripture.1-corinthians-15", "src.ccc.main"] },
    ],
    scriptureEvidence: [
      scripture("1 Corinthians 15:1-8", "Paul offers a compact received proclamation focused on Christ's saving death, burial, resurrection, and witnessed appearances.", "src.scripture.1-corinthians-15"),
      scripture("Matthew 28:18-20", "The risen Jesus joins Trinitarian Baptism, disciple-making, and continuing instruction.", "src.scripture.matthew-28"),
      scripture("Acts 2:22-42", "Peter proclaims Jesus' death, resurrection, and lordship, calls for conversion and Baptism, and the new believers enter apostolic communal life.", "src.scripture.acts-2"),
      scripture("Ephesians 4:1-16", "The one body grows in unity, truth, love, and maturity under Christ its head.", "src.scripture.ephesians-4"),
    ],
    catechismMagisterialEvidence: [
      magisterial("CCC 1-3", "The Catechism opens with God creating and calling humanity to share divine life, then sending the Son and Spirit and the Church to announce communion."),
      magisterial("CCC 422-429", "Christian catechesis transmits and seeks communion with Jesus Christ."),
      magisterial("CCC 571-573", "The Paschal Mystery stands at the centre of the Good News."),
      magisterial("CCC 748-750", "The treatment of the Church begins with the Holy Spirit's work in bringing the Father's plan to completion."),
      magisterial("Evangelii Gaudium 164-165", "Francis describes the foundational proclamation as Trinitarian, Christ-centred, grace-filled, and continually necessary.", "src.francis.evangelii-gaudium"),
    ],
    patristicHistoricalEvidence: historical("Creeds and catechetical summaries served as concise rules that oriented learners to the scriptural whole without replacing it.", [
      { summary: "Cyril presents the Creed as a concise form to be learned and then unfolded through scriptural teaching.", sourceId: "src.cyril.catechetical-lectures", locator: "Catechetical Lecture 5" },
      { summary: "Irenaeus appeals to an ordered apostolic rule of faith shared across the churches when summarizing creation, Christ, the Spirit, and final fulfillment.", sourceId: "src.irenaeus.against-heresies", locator: "Against Heresies I.10; III.3" },
    ]),
    importantDistinctions: [
      distinctions("What a short account can and cannot do", [
        ["Summary", "Orients the listener to the whole through its centre and major movements", "Creates a truthful map for later learning"],
        ["Proof", "Offers evidence sufficient for a disputed conclusion", "Usually requires more time, sources, and engagement with alternatives"],
        ["Testimony", "Describes how the speaker has encountered and lived the faith", "Can be powerful but does not replace the Church's public claim"],
        ["Adaptation", "Changes vocabulary and entry point for a real listener", "Must preserve the substance rather than conceal it"],
      ]),
    ],
    strongObjection: "A two-minute account either oversimplifies Catholicism into generic Christianity or overwhelms the listener with Catholic additions.",
    opposingPosition: "The objection identifies the tension between brevity and completeness. A generic summary may hide the Church and sacraments, while a denominational inventory may obscure Christ and the Gospel.",
    catholicResponse: "The hierarchy of truths resolves the false choice. A summary can state the central Trinitarian and Christological mystery and include the Spirit's ecclesial and sacramental work as part of the same saving movement. It openly admits that it is a doorway. The listener's next question then determines which claim receives evidence and detail.",
    commonMistakes: [
      "Opening with a secondary Catholic-Protestant controversy.",
      "Speaking of Jesus without the Father and Holy Spirit.",
      "Ending at forgiveness while omitting incorporation, discipleship, and resurrection hope.",
      "Treating memorized wording as more important than listening.",
      "Presenting the summary as though it proved every claim it names.",
    ],
    practicalSpiritualApplication: "Draft a 180- to 220-word account using the five movements. Say it aloud in under two minutes. Ask a trusted listener to mark where Christ disappears, jargon accumulates, or a claim sounds unsupported, then revise.",
    summary: "A concise Catholic account follows the triune saving movement from creation and sin through the incarnate Son's Paschal victory, the Spirit's work in Church and sacraments, grace-enabled discipleship, and final hope. It is a faithful doorway that invites the listener's next real question.",
    reviewPrompts: [
      "Name the five movements of the proposed two-minute account.",
      "What makes the account distinctly Catholic without making it a list of disputes?",
      "Why should the speaker end with a question?",
    ],
    practiceIntents: [
      ["short_response", "Compose a concise Trinitarian and Christ-centred account of Catholic faith."],
      ["scenario", "Adapt the entry point for different audiences without changing the substance."],
    ],
    references: [
      reference("src.scripture.1-corinthians-15", "1 Corinthians 15:1-8", "Compact apostolic Gospel proclamation"),
      reference("src.scripture.matthew-28", "Matthew 28:18-20", "Trinitarian mission and initiation"),
      reference("src.scripture.acts-2", "Acts 2:22-42", "Paschal proclamation, conversion, Baptism, and Church"),
      reference("src.scripture.ephesians-4", "Ephesians 4:1-16", "Ecclesial unity and maturity under Christ"),
      reference("src.ccc.main", "CCC 1-3; 422-429; 571-573; 748-750", "Whole-plan and Christ-centred synthesis"),
      reference("src.francis.evangelii-gaudium", "Sections 164-165", "Foundational proclamation"),
      reference("src.jp2.catechesi-tradendae", "Sections 5-6", "Christocentric and audience-aware catechesis"),
      reference("src.cyril.catechetical-lectures", "Catechetical Lecture 5", "Creedal summary for formation"),
      reference("src.irenaeus.against-heresies", "Books I.10 and III.3", "Early rule-of-faith synthesis"),
    ],
    relatedLessonIds: ["les.catholic-foundations.foundations.01", "les.catholic-foundations.distinctions.02", "les.catholic-foundations.synthesis.02"],
    graphCategoryIds: ["trinity", "christology", "historical"],
    doctrinalClassifications: ["dogma", "doctrine", "historical_claim"],
    comparativeTraditions: [],
  },
  {
    phase3LessonId: "les.catholic-foundations.synthesis.02",
    centralQuestion: "Why should formation normally come before argument in Catholic apologetics?",
    learningObjectives: [
      "Explain how doctrinal, spiritual, moral, and interpretive formation make apologetic judgment possible.",
      "Distinguish formation before argument from indefinite delay or avoidance of urgent questions.",
      "Create a safe response path for questions that exceed the learner's competence.",
    ],
    shortDirectAnswer: "Formation comes first because a defender must know the faith as an integrated life before judging sources, classifying claims, or representing objections. This priority does not forbid early answers; it makes them proportionate, supervised, honest about limits, and ordered to growth in Christ.",
    fullExplanation: [
      heading("Apologetics depends on formed judgment"),
      paragraph("A database can retrieve citations, but it cannot by itself determine whether a question is pastoral, historical, doctrinal, or merely verbal. Formed judgment recognizes the hierarchy of truths, the type and authority of a source, the strongest relevant objection, and the difference between what the Church teaches and what one Catholic thinks.", ["src.ccc.interpretation", "src.vatican2.unitatis-redintegratio"]),
      heading("The apologist is also a disciple"),
      paragraph("Christian truth is ordered to communion with God and a life of charity. Scripture joins teaching with maturity, virtue, worship, patience, and action. Formation therefore includes prayer, sacramental life, moral conversion, intellectual habits, and accountability. These do not guarantee correctness, but their absence makes knowledge easier to weaponize.", ["src.scripture.ephesians-4", "src.scripture.colossians-3", "src.scripture.james-1", "src.ccc.main"]),
      heading("Answer now, learn next, refer when needed"),
      paragraph("Beginners will encounter urgent questions before completing a curriculum. They can give the short answer they actually know, cite an authoritative source, and name what requires further study. High-risk matters involving trauma, canon law, medicine, abuse, or contested history should move to qualified pastoral or professional review. Formation is a path of increasingly responsible participation, not a gate that forbids all speech.", ["src.scripture.1-peter-3", "src.scripture.2-timothy-2"]),
    ],
    essentialTerminology: [
      { term: "Formation", definition: "The integrated shaping of understanding, worship, character, prayer, habits, and mission in Christ and the Church.", sourceIds: ["src.jp2.catechesi-tradendae", "src.ccc.main"] },
      { term: "Competence", definition: "Demonstrated ability to handle a defined kind of question with suitable knowledge, method, and accountability.", sourceIds: ["src.scripture.2-timothy-2"] },
      { term: "Referral", definition: "Directing a question to a pastor, theologian, historian, canonist, clinician, safeguarding officer, or other qualified person when the issue exceeds one's role.", sourceIds: ["src.scripture.ephesians-4"] },
      { term: "Intellectual humility", definition: "Truthful recognition of one's knowledge, evidence, fallibility, and dependence on God and others.", sourceIds: ["src.scripture.james-1"] },
    ],
    scriptureEvidence: [
      scripture("Ephesians 4:11-16", "Christ gives diverse ministries so the body grows toward doctrinal stability, mature judgment, and truth spoken in love.", "src.scripture.ephesians-4"),
      scripture("Colossians 3:12-17", "Teaching belongs within compassion, humility, patience, forgiveness, peace, worship, and gratitude.", "src.scripture.colossians-3"),
      scripture("2 Timothy 2:14-26", "A teacher must handle truth carefully, avoid foolish quarrels, and correct with patient gentleness.", "src.scripture.2-timothy-2"),
      scripture("James 1:19-27", "Listening, disciplined speech, moral action, and care for the vulnerable expose merely verbal religion.", "src.scripture.james-1"),
    ],
    catechismMagisterialEvidence: [
      magisterial("Catechesi Tradendae 5-6", "Catechesis is centred on Christ and ordered to communion with him, not merely the transfer of religious data.", "src.jp2.catechesi-tradendae"),
      magisterial("CCC 426-429", "At the heart of catechesis is a Person, and the teacher transmits Christ's teaching rather than a private system."),
      magisterial("CCC 1691-1698", "Moral catechesis is life in Christ, grace, beatitude, virtue, and the Holy Spirit, not detached rule memorization."),
      magisterial("CCC 2558-2565", "Prayer is living covenant and communion, making it intrinsic to formation rather than an optional preface to study."),
      magisterial("Unitatis Redintegratio 11", "Ecumenical explanation requires qualified knowledge, fidelity, charity, humility, and proportion.", "src.vatican2.unitatis-redintegratio"),
    ],
    patristicHistoricalEvidence: historical("The ancient catechumenate treated learning as preparation of belief, conduct, prayer, and sacramental participation rather than immediate specialization in controversy.", [
      { summary: "Cyril addresses candidates preparing for initiation and stresses receptive, disciplined participation in a sustained course of catechesis.", sourceId: "src.cyril.catechetical-lectures", locator: "Procatechesis" },
      { summary: "The Didache places moral formation before its instructions on baptism, prayer, Eucharistic practice, and community life.", sourceId: "src.didache", locator: "Didache 1-10" },
    ]),
    importantDistinctions: [
      distinctions("Formation and responsible participation", [
        ["Foundation", "Core grasp of Christ, the four-part faith, sources, and claim types", "Makes later specialization intelligible"],
        ["Supervised practice", "Low-risk explanations with sources and feedback", "Builds skill before public authority is assumed"],
        ["Specialist competence", "Deeper mastery of a defined doctrinal, historical, or comparative field", "Needed for high-complexity disputes"],
        ["Avoidance", "Refusal to engage merely because a question is difficult", "Not justified by the priority of formation"],
      ]),
    ],
    strongObjection: "People ask difficult questions now. Requiring formation first creates passive Catholics who never share the faith and leaves the internet unanswered.",
    opposingPosition: "The objection rightly resists perfectionism and recognizes that ordinary believers have real baptismal witness and can communicate truths they genuinely know. Endless preparation can become fear or institutional control.",
    catholicResponse: "Formation is staged, not all-or-nothing. A beginner can testify, give a clear foundational answer, and point to reliable sources. What formation forbids is pretending to specialist certainty. The safe pattern is: clarify the question, state the known Catholic teaching, distinguish evidence from inference, flag uncertainty, and refer high-risk issues. This produces active disciples whose responsibility grows with competence.",
    commonMistakes: [
      "Waiting for total knowledge before ever speaking about Christ.",
      "Confusing access to many citations with competence to interpret them.",
      "Answering pastoral pain as though it were only an argument.",
      "Using prayer language to avoid evidence or using evidence to avoid conversion.",
      "Failing to refer legal, medical, safeguarding, or trauma-related issues to qualified help.",
    ],
    practicalSpiritualApplication: "Create a three-level response card: 'I can explain,' 'I can research with sources,' and 'I must refer.' Place five common questions under the appropriate level and name one trusted source or person for each referral.",
    summary: "Formation gives apologetics its Christian centre, conceptual map, interpretive discipline, virtues, and accountability. It precedes argument as a normal order, while staged practice lets beginners witness truthfully and refer questions beyond their competence.",
    reviewPrompts: [
      "Which dimensions of formation are necessary beyond doctrinal information?",
      "How does staged practice answer the charge of indefinite delay?",
      "What kinds of question require referral rather than an improvised apologetic answer?",
    ],
    practiceIntents: [
      ["scenario", "Choose among answering, researching, and referring in a realistic question."],
      ["short_response", "Explain why formation and active witness are not opposites."],
    ],
    references: [
      reference("src.scripture.ephesians-4", "Ephesians 4:11-16", "Ministry, maturity, and truth in love"),
      reference("src.scripture.colossians-3", "Colossians 3:12-17", "Teaching within formed Christian character and worship"),
      reference("src.scripture.2-timothy-2", "2 Timothy 2:14-26", "Competent, patient, and gentle instruction"),
      reference("src.scripture.james-1", "James 1:19-27", "Listening and enacted religion"),
      reference("src.scripture.1-peter-3", "1 Peter 3:13-16", "Prepared and gentle witness"),
      reference("src.ccc.main", "CCC 426-429; 1691-1698; 2558-2565", "Christ-centred, moral, and prayer formation"),
      reference("src.ccc.interpretation", "CCC 84-90", "Claim classification and the hierarchy of truths"),
      reference("src.jp2.catechesi-tradendae", "Sections 5-6", "Communion with Christ as catechetical aim"),
      reference("src.vatican2.unitatis-redintegratio", "Section 11", "Qualified and charitable explanation"),
      reference("src.cyril.catechetical-lectures", "Procatechesis", "Ancient catechumenal preparation"),
      reference("src.didache", "Chapters 1-10", "Formation joined to initiation and worship"),
    ],
    relatedLessonIds: ["les.catholic-foundations.objections.01", "les.catholic-foundations.objections.02", "les.catholic-foundations.synthesis.01"],
    graphCategoryIds: ["historical", "christology"],
    doctrinalClassifications: ["doctrine", "discipline", "historical_claim"],
    comparativeTraditions: [],
  },
];
